---
title: "case3_teacher_rank"
author: "yy"
date: '2022-04-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 买个中小学教师职称需要多少钱？

为了写篇关于中小学教师职称的文章，本打算在裁判文书网找一些有关职称评审的行政案件，却意外地发现许多与职称评审有关的刑事案件，即公职人员在中小学职称评审中受贿的案件，有些是单独职称评审受贿案件，有些职称评审受贿只是系列案件之一。下文摘录一些案件中的事实，我们可以了解一下中小学职称评审舞弊现象的表现。

"2006年至2013年4月期间，被告人杨某在担任云南省宣威市**教育局人事科副科长**职位期间，利用职务之便，先后分**33次**收受王某1、徐某1、刘某1等36名教师送给的人民币共计99300元。单次受贿金额为2000－6000元不等。"

"被告人朱某于2006年9月至2016年1月间任浙江省缙云县**教育局某部门科长**，2015年的一天，被告人朱某在章某高级职称评审过程中提供帮助，使章某顺利通过当年评审获得高级职称评定。为此，章某送给朱某现金人民币20000元。2016年的一天，被告人朱建明接受宋某的请托，在其朋友杨某高级职称评审过程中提供帮助，使杨某顺利通过当年的评审获得高级职称评定。为此，杨某通过宋某送给朱某现金人民币20000元。"

"2013年9月，河南安阳市殷都育才中学教师刘某为了能通过教师职称评审，请求殷都区**人社局局长**冯某帮忙，刘某先后两次到冯晓的办公室，给了冯晓两张建设银行活期存单，每张存单内有现金人民币1万元，两张共计2万元。2013年7月，安阳市殷都育才中学教师齐某为了能通过教师职称评审，请求殷都区人社局局长冯某帮忙，齐某在冯某办公室，给冯某一张工商银行卡，内存现金人民币6000元。"

"2010年10月至2011年12月份期间，刘海军作为河南省历史学科的中学教师高级专业技术职务任职资格**评审委员会委员**，收受董保红、毕辉、王玉林、陈莉、姜爱民、张弛、贺虎山、卢鹤仙、乔付民等人共计51000元，为董保红等人在河南省中小学教师高级职称评定一事中帮忙。后因毕辉、陈莉未通过评定，刘海军将其中的8000元予以退还。"

"2009年至2016年，被告人张学海在担任宁夏中卫市**某中学校长**期间，先后为本校教师王某甲、张某甲等七名教师在职称评定过程中提供帮助，先后收受该七名教师财物共计人民币50000元。"

这些是通过刑事诉讼进入司法审查中的案件，职称评审腐败到底有多严重，即那些没有进入司法领域、或者自始至终没有被的职称评审舞弊到底有多少，我们是不清楚的。职称评审舞弊无疑是危害很大，它造成了不公，损害了其它教师的合法权益；它破坏了职称的激励功能，起到不良的示范作用，教师丧失了努力的动力；它恶化教师的职业环境，不利吸引优秀的人才进入教师队伍。

职称晋升几乎是中小学教师增薪的唯一途径，无怪乎一些人诉诸于这些非常规路径。那么，我们如何解决这个问题，途径无外乎加强监督，首先是来自于行政部门的监督，但这是不够的，正好上面案件所示，有时候主管的行政部门正是滥权者本人。其实，最好的监督总是来自于权利受损者，制定应当让让权益受损者能够实现对职称评审工作的监督，这无外乎两个方面，一是评审的规则、过程与结果是公开的，只有信息公开，监督可有可能；一是有一个中立主体能够合法合规的处理这些案件。关于后者，我认为，允许将职称评审行为纳入行政诉讼的受案范围，将有利于监督以上权力的行使。

中小学教师职称评审涉及行政权力和专家权力的自由裁量，包括学校管理层、评审委员会专家、以及负责召集专家的教育行政部门，还有负责最终审核的人社部门。任何一个主体不公正行使职权，都会影响职称评审的结果。且校长、评审专家和行政部门工作人员也比较容易形成利益共同体，不利于普通教师的权益保护。《职称评审管理暂行规定》（2019年）将职称评审监督主体设定为人社部门和教育行政部门，忽略了中小学教师职称评审的特殊性，其它系列职称评审多数由单位完成，比如高校的职称评审，而中小学教师职称评审，教育行政部门和人社部门是重要的决定主体，由行政部门监督行政部门行使职权，有违正当程序原则。正是如此，教师申诉制度在解决职称评审争议方面的功能也有限。综上，迫切需要将中小学教师职称评审纳入到行政诉讼的受案范围当中，接受司法监督。
