---
title: "case01_teacher_recruitment"
author: "yy"
date: "12/6/2021"
output: html_document
---

# 应聘教师被取消面试资格，是否可以提起诉讼？

编者按：《教师法》修订正在进行中。近些年，越来越多教师试图通过司法解决权益受损问题。司法是《教师法》的适用现场，探讨教师权益的司法案例将有助于发现和回应教师人事管理法制建设中的现实问题。因此，本号将推出一组中小学教师权益相关的案件分析文章，今天第一期是一个关于应聘中小学教师被取消面试资格的案例。

## 基本案情

2019年8月12日，湖南省怀化市会同县教育局发布《会同县2019年第二次公开招聘中小学教师公告》，面向社会公开招聘中小学教师30名，其中小学英语教师4名。方某文报名参加小学英语教师岗位招聘，并以笔试成绩第8名的成绩入围面试。2019年9月2日，会同县教育局发布《会同县2019年第二次公开招聘中小学教师面试公告》，方某文位列面试人员名单。公告载明：参加面试的考生必须于2019年9月6日到会同县教育局人事股报到。该公告还有两条注意事项如下：1、考生必须携带本人有效身份证、笔试准考证，在面试当日上午7：20前到达指定考点候考。上午7：20未到者，作自动弃权处理，取消面试资格。未携带有效身份证、笔试准考证的，不得参加面试。2、面试考生应当遵守面试纪律，文明应考。要求统一着装，穿白色衬衫上衣，黑色长西裤（服装自备），不准穿有职业特征的服装，仪表符合职业规范，不准佩戴任何饰品进入面试考场。2019年9月7日，方某文着白色衬衫，外套黑色长裙，6：50提前赶到了考点会同县城北学校，但会同县教育局监考工作人员以其未按规定着装，禁止进入候考区，方某文与工作人员沟通无效后，其丈夫将所穿西裤换给方某文，此时，已是上午7时23分，会同县教育局监考工作人员以超过规定时间禁止方某文进入候考区，致使其未能参加面试。另需说明的是，方某文参加面试时已怀孕8个月。后方某文对会同县的处理决定不服向人民法院提起诉讼，请求法院判令：确认2019年9月7日会同县教育局以不穿黑色西裤为由剥夺原告面试资格的行为违法，赔礼道歉、赔偿损失人民币一元并重新组织面试。

## 法院判决

法院认为，《湖南省行政程序规定》第三条规定："行政机关应当依照法律、法规、规章，在法定权限内，按照法定程序实施行政行为。"第六十二条规定："行政机关在行政执法过程中应当依法及时告知当事人、利害关系人相关的执法事实、理由、依据、法定权利和义务。行政执法的告知应当采用书面形式。情况紧急时，可以采用口头等其他方式。但法律、法规、规章规定必须采取书面形式告知的除外。"根据上述规定，行政机关应当按照行政实体法和程序法的规定切实履行法定职责，在行政管理中依法保障行政相对人的合法权利。此案被告会同县教育局监考工作人员作出的取消原告面试资格的行为直接影响到原告的权利义务，被告应当采取适当的方式告知原告相关的执法事实、理由、依据、权利和义务，听取原告的申辩，被告会同县教育局并未提交证据证明其履行了上述程序，属程序违法。《中华人民共和国国家赔偿法》第二条规定："国家机关和国家机关工作人员行使职权，有本法规定的侵犯公民、法人和其他组织合法权益的情形，造成损害的，受害人有依照本法取得国家赔偿的权利。"本案被告会同县教育局工作人员因行使职权侵犯原告合法权利造成损害，被告会同县教育局应承担赔偿责任。依照《中华人民共和国行政诉讼法》第七十四条第二款第（一）项、《中华人民共和国国家赔偿法》第二条、第四条第（四）项之规定，判决如下：一、被告会同县教育局取消原告方某文面试资格的行为违法。二、被告会同县教育局赔偿原告方某文损失人民币一元。三、驳回原告方某文的其他诉讼请求。原告方某文不服该判决向上级人民法院提出上诉，在审理过程上，（因本文无法知晓的原因）方某文递交撤诉申请书，自愿撤回对本案的起诉和上诉。二审法院裁定：一、准许方某文撤回起诉和上诉；二、本案一审判决不再发生法律效力。

## 案件点评

（一）对教师招聘处理决定不服是否可以提起行政诉讼？

答案是肯定的。这在很大程度上归功于新《行政诉讼法》出台以后对行政诉讼受案范围的扩充。理由如下：其一，法院一般认为教育行政部门或者人社部门在组织招聘时是履行法规或规章规定的职权。《事业单位公开招聘人员暂行规定》（2006年）第六条规定："政府人事行政部门是政府所属事业单位进行公开招聘工作的主管机关。政府人事行政部门与事业单位的上级主管部门负责对事业单位公开招聘工作进行指导、监督和管理"。《事业单位人事管理条例》（2014年）第三条规定："县级以上地方各级事业单位人事综合管理部门负责本辖区事业单位人事综合管理工作。事业单位主管部门具体负责所属事业单位人事管理工作"。其二，《行政诉讼法》第十二条规定人民法院受理公民、法人或者其他组织提起的下列诉讼：（十二）认为行政机关侵犯其他人身权、财产权等合法权益的。行政部门作出取消应聘资格的行为，可能侵犯应聘人员的劳动权。因此，法院认为行政部门在教师公开招聘过程中做出的处理决定是其履行法定职权过程中做出了直接影响行政相对人合法权益的行为，行政相对人可以提起行政诉讼。另外，2018年《事业单位公开招聘违纪违规行为处理规定》第二十条亦规定："应聘人员对处理决定不服的，可以依法申请行政复议或者提起行政诉讼。"

（二）会同县教育局的行为是否违法？

本案法院以程序违法确认会同县教育局取消原告方某文面试资格的行为违法，是法院在审理事实争议较大案件惯常的处理方式：能以程序问题结案的则以程序性问题结案，避免对实体性问题裁判。其实，本案从实体上来看，会同县教育行政部门取消方某文的面试资格也是没有依据的。其一，原告虽然7点23分才到候考区，按照《面试公告》的规定"上午7：20未到者，作自动弃权处理，取消面试资格"，是可以取消面试资格的，但事实上原告6：50已经到达考点，会同教育局工作人员以着装不合要求而禁止原告入场所，这才导致时间损耗，而根据《面试公告》"要求统一着装，穿白色衬衫上衣，黑色长西裤（服装自备），不准穿有职业特征的服装，仪表符合职业规范，不准佩戴任何饰品进入面试考场"。可知，不穿黑色长西裤应当是倡导性的规定，不穿可能影响面试时的表现得分，而不应当是禁止应聘者进入考场的理由。二、应聘者已经怀孕8月，穿长西裤确有不便，且应聘者已经变换成了亦属于正装的黑色长裙，教育行政部门应当在不影响招聘公正性的情况下，给予孕妇以基本的人文关怀。因此，本案法院应当以实体要件不符，确定教育行政部门行为违法，而不是仅以程序性问题确定教育行政部门的行为违法。

（三）立法建议

近些年，教师公开招聘纠纷频频进入司法领域，涉及笔试、面试、体检、政审等各个环节。比如所学专业与应聘学科不一致而被取消资格的，身高不高于1.5米而被取消应聘资格的，违反计划生育政策而被取消应聘资格的，等等。法院已经逐步受理此类案件。这是一件很好的事情，实现了司法监督作用，促进了行政机关在教师招聘过程做到公开、公平、公正，依法履行为中小学补充合格教师的职能，也保障了应聘者的合法权益。不同于教师权益的其它纠纷，公开招聘得以进入司法领域，除了上文提到的法制原因之外，还因为应聘者没有进入到教师队伍，不受教育行政部门的约束，其在应聘教师过程中，是一个纯粹的行政相对人，而一旦进入教师队伍，其身份已经不完全是一个纯粹的行政相对人。这里面包括了所谓的内部法律关系的问题，比如，教育行政部门评聘职称和给予教师处分行为，如果教师不服，提起诉讼，法院是不受理的。因为此时，教师并不仅仅是纯粹的行政相对人。教师公开招聘相关诉讼多的另一个原因在于，应聘者败诉后的风险较小，败诉也不会损失什么，如果胜诉，则可能应聘为教师。而作为一个在学校的教师，如果起诉学校，即使胜诉，也可能在今后工作中面临打击报复的风险。 关于教师招聘工作的法制建设水平，可以说是这些年教师法制建设做得比较好的一个方面，但有两点需要完善：其一，关于教师招聘主体，地方政府一般是组织一个由教育、人事、编制和纪检等部门构成的领导小组和相应的办公室具体操作，有些地方是教育行政部门主导，有些地方是人事综合管理部门主导。因此，有时应聘者在主张权利时，找不到维权的适格对象，考虑到教师招聘具有很强的专业性，应当统一赋予教育行政部门在中小学教师招聘过程的主导角色。其二，虽然根据行政诉讼法的一般理论可以得出，应聘者可以提起诉讼，但还是缺乏直接的法律依据，虽然《事业单位公开招聘违纪违规行为处理规定》第二十条有规定，但其仅属于部门规章，根据《行政诉讼法》第十二条的规定："除前款规定外，人民法院受理法律、法规规定可以提起诉讼的其他行政案件"，法律、法则才可以设定公民可提行政诉讼的事项。因此，在《教师法》中应当规定应聘者对教师招聘处理决定不服可以提起诉讼。
