---
title: "case02"
author: "yy"
date: "12/12/2021"
output: html_document
---

# 编制内教师聘用合同到期终止，单位不续签怎么办？

编者按：《教师法》修订系列案例分析第二期，一个关于聘用合同到期单位不续签的案例。2002年之后，中小学教师人事管理逐渐引入了聘用合同制度，随之而来的则是合同的期限制度，合同到期终止，双方权利义务归于消灭，教师职业安全保障则取决于传统约束。在普通劳动者和和公务员的职业安全保障制度建立之后，包括中小学教师在内的事业单位工作人员的职业安全保障是一块制度残缺。

## 基本案情

舒某系丰台八中音乐老师，双方签订有期限为2015年8月1日至2019年7月31日《北京市事业单位聘用合同书》，其中第二十一条约定"本合同期限届满前，甲方（丰台八中）应当提前30日将终止或续订聘用合同意向以书面形式通知乙方（舒某），经协商办理终止或者续订聘用合同手续"；第三十条约定"属于下列情形之一解除本合同的，甲方应根据乙方在甲方工作的年限，发给一定的经济补偿金：（一）甲方提出解除本合同的，乙方同意解除的；（二）符合本合同第十四条规定情形，由甲方单方面解除本合同的；（三）因甲方未履行本合同，乙方解除本合同的......"。2019年6月26日，丰台八中向舒某送达《舒某老师合同到期不再续签合同的通知》，内容载明"舒某老师：您的本期合同自2015年8月1日起至2019年7月31日止。经校务会研究决定，合同到期后学校不再与您续签合同。"2019年8月26日，舒某向北京市丰台区人事争议仲裁委员会提起仲裁，要求丰台八中支付终止聘用合同经济补偿金146500.32元、公开向其道歉、在全体教职工大会上公开宣布系单位在未与其协商的情况下单方不续签聘用合同非因其个人原因不续签、出示校务会成员名单及到期不续签合同的研究会议记录。2019年11月21日，丰台人事仲裁委裁决驳回舒某的各项仲裁请求。舒某不服，提起诉讼。

## 法院判决

一审法院认为，舒某与丰台八中系人事聘用关系，根据双方签订的《北京市事业单位聘用合同书》第二十一条约定，在聘用合同期限届满前，丰台八中应当提前30日将终止意向以书面形式通知舒某，现丰台八中于2019年6月26日书面通知舒某其于2019年7月31日到期的聘用合同不再续签，已履行合同约定的告知义务。参照《国务院办公厅转发人事部关于在事业单位试行人员聘用制度意见的通知》及根据双方签订的《北京市事业单位聘用合同书》约定，合同到期终止并非支付经济补偿的情形，故对舒某要求丰台八中支付终止聘用合同的经济补偿的诉讼请求，法院不予支持。舒某要求丰台八中向其公开道歉、在全体教职工大会上公开宣布非因其个人原因而系未与其协商单方不续签聘用合同以及出示校务会成员名单和到期不续签聘用合同的研究会议记录的诉讼请求，不属于人民法院受理人事争议案件的受案范围，法院不予处理。判决：驳回舒某的诉讼请求。舒某不服判决，提起上诉。二审法院驳回上诉，维持原判。

## 案例点评

（一）可否主张续签合同？

这个案子比较特殊一点是，事业单位的聘用合同到期，单位尽然不续聘，这对进入事业编制的中小学教师而言，是极其低频的事件。在我国事业单位人事管理的传统下，纳入编制管理的教师，与学校之间的人事关系有终身的性质，除非出现法定的解除聘用合同的条件，比如说违纪开除，聘用合同到期，一般自动续签的。但这个案子破了这一传统。聘用合同到期，单位不予续聘。此时，教师是否有司法上的请求权，要求学校予以续聘呢？答案是没有的。因为这是聘用合同期限制度的本质特征，合同到期，双方权利义务终止。因此，在法律上，对于聘用合同到期，单位不续签的行为，教师是没有法律依据要求单位必须续签的。

（二）可知主张补偿金？

聘用合同到期终止是否可以申请补偿金呢？补偿金是劳动法上的一个概念。根据《劳动合同法》第四十六条的规定，在一定情形下，用人单位要向劳动者支付经济补偿，其中情形之一是"除用人单位维持或者提高劳动合同约定条件续订劳动合同，劳动者不同意续订的情形外，依照本法第四十四条第一项规定终止固定期限劳动合同的"。因此，劳动合同到期，如果不是劳动者不愿续签，而是用人单位不愿续签的话，用人单位需要支付劳动者经济补偿。这也是本案原告提起诉讼请求的理由。但本案涉及的是聘用合同，而非劳动合同，根据《劳动合同法》第九十六条："事业单位与实行聘用制的工作人员订立、履行、变更、解除或者终止劳动合同，法律、行政法规或者国务院另有规定的，依照其规定；未作规定的，依照本法有关规定执行"。因此，是否应当支付经济补偿要看国务院是否"另有规定"。针对经济补偿金的问题国务院确另有规定，即《国务院办公厅转发人事部关于在事业单位试行人员聘用制度意见的通知》。其第六项规定在聘用合同解除环节需支付经济补偿的情况，这一规定也反映在本案《聘用合同》第三十条中。聘用合同终止不是用人单位支付经济补偿的条件，因此法院没有支持原告的请求。

（三）立法建议

通过本案可以揭示我国在聘用合同制度建设上的两点不足。其一，聘用合同没有像劳动合同制度一样的无固定期限合同。虽然《事业单位人事管理条例》第十四条规定："事业单位工作人员在本单位连续工作满10年且距法定退休年龄不足10年，提出订立聘用至退休的合同的，事业单位应当与其订立聘用至退休的合同"。该规定对于中小学教师而言，较为苛刻。按男性教师法定退休年龄60计，也就意味着50岁之后才有可能提出订立至退休的合同。固定期限的合同意味着教师聘用合同到期，用人单位不续聘，则没有任何法律后果。一方面，劳动合同有无固定期限合同，公务员是没有期限的，甚至大学教师都有终身教职；另一方面，国际上其它国家中小学教师要么是公务员的无固定期限，要么是无终止期限的劳动合同。而中小学教师还只是定期签订3年或5年的固定期限合同，既不符合实践，也不符合对教师权益的保护。其二，根据现有规定，聘用合同到期不续不是支付经济补偿金的条件之一。那么，从合理性来讲，学校是否应当支付呢？这需要理解经济补偿金的性质，经济补偿金本质上是一种救助性质的，是保障劳动者失去工作后的基本生活一种临时的救助金。根据《公务员辞退规定》第十六条规定：未参加失业保险的，领取辞退费。辞退费和普通劳动者的"经济补偿金"在性质上一样的。也就是说，同样是关系解除，普通劳动者有经济补偿金，公务员有辞退费，但如果是像中小学教师一样的事业单位工作人员，是什么都没有的，这显然是不合理的。这是事业单位聘用合同管理制度建设中残缺的一块。关系终止后获取用人单位一定的经济补偿是中小学教师应当享有的社会保障权利。因此，在《教师法》修订中要确定中小学教师在聘用合同到期单位不予续签时可以获得经济补偿的权利。
