---
title: "中学教师因'末位淘汰'被下调至乡小，可否起诉教育局？"
author: "yy"
date: "12/21/2021"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

**编者按：**《教师法》修订系列案例分析第三期聚焦一个因教师调动而产生的纠纷，该案经历漫长的5次审判，从中可以折射出中小学教师交流轮岗政策与聘用合同之间的制度冲突，迫切需要立法回应。

## 基本案情

黄新威于2016年与白土中学签订聘用合同，是白土中学一名公办教师。2018年初，韶关市曲江区根据上级有关单位的部署开展中小学教师"县管校聘"教育改革工作，白土中学为此制定并经全体教职员工表决通过了《曲江区白土中学"县管校聘"实施方案》，该方案确定在该校实施教职员竞聘上岗。同时，根据曲江教育局于2018年7月6日发出的通知确认该校教职员岗位数为46人，该岗位数量低于当时白土中学在编在职的教职员数量。因此，竞聘上岗注定有部分教师落聘。但是，"落聘"的教师可以参加第二轮其他未满编学校的竞聘，第二轮竞聘还是"落聘"者或者不参加第二轮竞聘的教师，则统一由教育局统筹安排，如教师不参加竞聘或者竞聘失败且不同意教育局统筹安排的，则仍然可以留在原学校，但工作岗位处于"待岗"状态，待岗期间仅发放原来70%的工资，待岗期限为一年，一年之后经考核不合格，则退出教学岗位并转岗到工勤岗位或者由用人单位解除聘用合同。白土中学竞聘上岗的结果是，黄新威与其余10名教师以打分"未位淘汰"的方式被调动至小学（其中6名在白某学小学，3名在白某心小学白沙学校，1名在白某心小学大村小学，1名在曲江区一小）。其后，黄新威以本次"县管校聘"过程中存在违法违规现象，也放弃第二轮跨校竞聘的机会，并多次前往教育部门、信访部门和纪检部门反映情况，但上述部门均未作出白土中学在"县管校聘"过程中存在违法违规行为的认定。2018年9月13日，曲江教育局出具韶曲人字第NO.0001094号《调动介绍信》，内容为"白土中心小学大村小学：兹介绍黄新威同志等壹名到你处安排工作，请接洽。附名单：黄新威。限2018年9月17日前报到。"
黄新威在签收时注明了是有条件接受调令，注明如果被告的"县管校聘"是违法违规的，那么对其调动就是不合法的。黄新威按照《调动介绍信》的内容前往大村小学任教。其后，韶关市曲江区白土镇中心小学要求与黄新威签订聘用合同，黄新威以案件未了结拒绝签订并坚持提起本案行政诉讼。2018年10月26日，黄新威向一审法院提起行政诉讼，诉讼请求为：一、判令曲江教育局撤销其在2018年9月13日对黄新威的工作调动介绍信。二、判令曲江教育局、白某中学赔偿黄新威精神损失费及各种材料打印等费用1000元。三、本案诉讼费由曲江教育局、白土中学负担。另外，就其与白土中学之间因聘用合同发生的争议，黄新威并未寻求仲裁或者民事诉讼途径解决。黄新威前往大村小学任教后，其享受的福利待遇相比起在白土中学任教还略高出80元/月。

## 法院判决

本案经历了两轮五次审判。第一轮一审法院认为，被告曲江区教育局出具《调动介绍信》的行为，并非其在实施行政管理活动中行使行政职权作出的行为，不属于行政行为，因此不属于人民法院行政诉讼的受案范围，为此裁定驳回了原告起诉。第一轮二审法院认为，曲江教育局出具《调动介绍信》给教师的行为，是黄新威在原用人单位白某中学采取"末位淘汰"失去在该中学执教资格后，由曲江教育局介绍到其他学校的一种对行政机关工作人员之外事业单位人员的调动行为，该行为不属于《行政诉讼法》第十二条第（三）项"行政机关对行政机关工作人员的奖惩、任免等决定"的行为，因为《行政诉讼法》和司法解释认为所谓的内部行为，是指行政机关对其工作人员作出的影响该工作人员权利义务关系的决定，并不包括行政机关针对行政机关之外公民的决定，即行政机关作出的行为具有很强的外部特征，企事业单位的工作人员在事实上处于行政相对人的法律地位，该调动行为对黄新威产生直接的权利义务影响，是行政诉讼的受案范围。但是，白某中学与黄新威之间的行为，属于事业单位与事业单位工作人员之间的人事争议，不属于人民法院行政诉讼的受案范围。撤销一审判决，发回重审。

第二轮一审法院认为，白土中学学属于事业单位，该中学并未依据法律、法规、规章的授权对原告黄新威作出任何行政行为，故原告黄新威以白某学为行政诉讼的被告，于法无据，其针对白土中学的起诉应依法予以驳回。但其针对被告曲江区教育局的起诉应依法继续审理。被告曲江区教育局系根据原告黄新威未能成功竞聘白某学教学岗位而面临其与白某学的聘用合同无法有效履行的实际情况，结合韶关市曲江区各中小学师资配备和岗位空缺情况，以《调动介绍信》的方式将原告黄新威介绍到大村小学任教。但被告曲江区教育局出具的《调动介绍信》并不具有强制效力，原告黄新威仍然可以按照"本校待岗"原因留在白某学，但其为避免在白某学待岗，亦根据《调动介绍信》的安排前往大村小学任教，而韶关市曲江区白土中心小学及大村小学，也在原告黄新威持有被告曲江区教育局开具的《调动介绍信》才为其安排教学岗位的工作并提出与之签订聘用合同，故被告曲江区教育局为原告黄新威开具《调动介绍信》的行为，并非强令原告黄新威必须到大村小学任教，而仅是根据《事业单位人事管理条例》第三条第三款"事业单位主管部门具体负责所属事业单位人事管理工作"的规定，对辖区内教师资源进行优化配置，被告曲江区教育局出具该《调动介绍信》，既有法律法规赋予的权限，同时也是根据原告黄新威的实际情况作出的行为，不违反正当程序原则。原告黄新威要求撤销该《调动介绍信》，理据不足，法院依法不予支持。

第二轮二审法院认为，《义务教育法》第三十二条第二款规定："县级人民政府教育行政部门应当均衡配置本行政区域内学校师资力量，组织校长、教师的培训和流动，加强对薄弱学校的建设。"从原则上授权县级人民政府教育行政部门具有组织教师进行"流动"的权利。由此可以确认，法律授权教育行政部门享有调动教师的权利，故曲江教育局调动黄新威的行政行为没有超越职权。由于曲江教育局调动黄新威的行为，是在白土中学实行"县管校聘"竞聘过程中黄新威未被该校聘用，该局以介绍的形式调动黄新威到其他学校从业所致，故黄新威在白土中学的落聘，并非曲江教育局的行政行为造成，而是白土中学采取的"末位淘汰"所致。由此可见，黄新威要求确认曲江教育局的调动行为违法，其提起的诉讼请求所持理由不充分。白土中学与黄新威之间的行为，属于事业单位与事业单位工作人员之间的事业单位人事争议，可以通过仲裁或者民事诉讼途径予以解决。黄新威不服二审判决，申请再审，被广东省高院以二审相同理由驳回。

## 案例点评

### 教育局的调动行为是否可诉？

本案核心争议之一是曲江区教育局做出的调动行为是否可以提起行政诉讼。根据行政诉讼法的规定，关键是看这一行为是否属于行政行为，即行政机关依职权做出的影响行为相对人具体权利义务的行为。首先，《事业单位人事管理条例》第三条第三款规定："事业单位主管部门具体负责所属事业单位人事管理工作"。《中华人民共和国义务教育法》第三十二条第二款规定："县级人民政府教育行政部门应当均衡配置本行政区域内学校师资力量，组织校长、教师的培训和流动，加强对薄弱学校的建设"。据此，教育局的调动行为是根据法律法规的规定履行职权的行为。但是，对教师是否属于行政相对人，法院对这一问题的判断是有分歧的。分歧的原因在于部分法院认为教师属于行政机关的工作人员，根据《行政诉讼法》的规定，行政机关对于行政机关工作人员的任免决定是排除司法审查的。本案一轮二审法院的判决显然突破了这一认识，承认"企事业单位的工作人员在事实上处于行政相对人的法律地位"，因此，教育局对于教师做出的调动决定是属于其履行职权而做出的影响行政相对人具体权利义务的决定，对该决定不满，是可以依法提起行政诉讼的。从司法保障教师合法权益的角度，这个案子的判决无疑是一大进步。

### 法院的判决是否合理？

虽然法院受理了本案，但最终还是没有支持黄新威的请求，其核心理由有二：黄新威与白土中学之间的关于履行聘用合同的纠纷应当通过仲裁或者民事诉讼解决，不是行政诉讼的受理范围；教育局做出的调动行为是在黄新威无法在原学校继续工作，基于管理职权而对其做出的安排，且不具有强制效力。表面看来，逻辑上是没有问题的。但问题是黄新威无法在白土中学继续工作这个事件本身是否是白土中学独立决定的事项，还是在教育局授权之下的行为？根据白土中学竞聘上岗的方案，如果未竞聘成功，可参与其它学校的竞聘，如果没有教育局的参与和肯定，该方案不可能执行，因此白土中学采取"末位淘汰"方式进行减员的做法很难说没有教育局的参与。虽然黄新威可以选择是否去大村小学，但是其若不去，则面临转岗、甚至聘用合同解除的风险，因此，也很难说这次调动完全没有强制效力。这个案子的难点在于一个调动行为涉及两个相对方：教育行政部门和学校，教师与前者之间的关系属于行政法律关系，与后者之间的关系属于民事法律关系。导致这一问题的制度原因在于，虽然教师与学校签订聘用合同，确定双方的权利义务关系，但实际上在诸多事项上，比如调动，却是教育行政部门在做决定。

### 采用末位淘汰的形式解除人事关系是否合规？

白土中学实行末位淘汰的方式确定转岗或者调离教师名单是在交流轮岗的政策背景之下进行的，根据《教育部、财政部、人力资源和社会保障部关于推进县（区）域内义务教育学校校长教师交流轮岗的意见》、《韶关市人民政府办公室关于推进全市基础教育学校公办教师"县管校聘"管理改革工作的意见（试行)》的规定，交流轮岗政策是为了支持薄弱学校发展。因此，往薄弱学位调配教师的原则是"择优选派"。但白土中学实行的却是"择差选派"，显然不合理。当然曲江县教育局名义上是在落实交流轮岗政策，但实际上是在解决师资资源校际间不均衡分配的问题。为什么不直接采用调配而冠以交流轮岗的名义？原因在于根据现行《教师法》的规定聘用合同是教师和学校之间签订的，跨校调动教师涉及与原学校之间的聘用合同解除的问题，以落实交流轮岗政策为由则比较好推行这一方案。但根据现有规定，交流轮岗并不是解除聘用合同的合法理由，《义务教育法》第三十二条规定教育行政部门可以组织教师流动，但是其与聘用合同制度并不没形成很好的制度衔接。由于义务教育资源的公共属性，也因为学生在校际间的分配随学龄人口流动而变化，教育行政部门跨学校调配教师是有正当理由的，但是聘用合同制度制约了该政策的施行。

### 立法建议

基于对本案的分析，对《教师法》的修订工作有三点建议。其一，承认教师在调动时行政相对人的法律地位，这样，针对教育行政部门实施的不合法的调动行为，教师才有有效的救济途径，因为针对这一问题教师申诉制度不可行，申诉的处理主体即是教育行政部门，这就面临运动员与裁判员是同一主体的尴尬境地；其二，在法律中规定教师调动的事由和程序，一方面是保障教师合法权益的需要，另一方面也为法院审理此类案件提供依据。其三，本案难点在于交流轮岗制度与聘用合同制度的冲突，解决这一冲突的方案也很简单，即中小学教师的聘用合同由教师与学校签订变更为与教育行政部门签订，真正将教师由"单位人"变为"系统人"，这样教育行政部门在调动教师时，则不会面临合法性的质疑。
