---
title: "中小学教师聘用合同制度的问题与完善"
author: "yy"
date: "6/2/2021"
output:
  workflowr::wflow_html:
    toc: true
editor_options:
  chunk_output_type: console
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 引言

1994《教师法》在事业单位人事制度改革之前就确定教师的聘用合同制度，全国性事业单位工作人员聘用制的推进是在2002年。聘用合同制度改革的初衷是放权，改革政府对学校管理过多过重的问题，通过聘用合同将中小学人事管理的相关事项下放给学校，强调学校与中小学教师自主决策能力。聘用合同制度重塑了中小学教师与学校、政府之间的关系，对中小学教师人事制度产生了深远的影响，但是聘用合同制度作为事业单位人事制度改革由人事综合管理部门整体进行推进的，其相关制度设计并没有考虑到基础教育发展与中小学教师人事管理实践的独特要求，在中小学教师聘用合同实施过程中产生了一系列问题，其一、行政部门与学校之间的关系分配问题，很多教师相关的事项的决定仍然存在于行政部门，学校的人事管理自主权并没有落实；其二、旨在打破人事关系终身性质的聘用期限制度并没有发挥应有的作用；其三、可约定事项比较狭小，教师在签订聘用合同时，并没有太多可以约定的空间，；其四、解除条件的问题，聘用合同纠纷的处理问题？
因此，在《教师法》修订的当下，有必须对上述问题做出回应。

## 聘用合同的主体问题

### 聘用合同主体设定存在的问题

《教师法》第十七条规定：教师的聘任应当遵循双方地位平等的原则，由学校和教师签订聘任合同，明确规定双方的权利、义务和责任。聘用合同由学校与教师签订，约定双方的权利、义务与责任的前提在于双方具有独立的意志，自主确定双方的权利、义务与责任。但是我国中小学人事制度改革的实践并没有给予中小学与教师之间可以自由约定的空间。中小学人事管理的权限主要存在于行政部门。学校对中小学教师合同的签订、聘用期限、工资待遇、岗位要求与工作条件、考核与奖惩和聘用合同的解除与终止等事项，根据现人事管理规定，在这些事项上中小学校并没有决定权。聘用合同的签订是由行政部门确定了招聘人员之后分配到学校，学校并不能决定是哪个应聘对象签订合同、聘用合同的期限也是行政部门确定的固定合同规定，学校没有权力设定与调整，教师的工资与社保待遇更是由国家和地方的政策进行确定，学校与教师无法自主约定工资结构与水平问题。关于工资与社保的约定，比如"甲方按照国家和北京市的有关规定，根据乙方完成工作任务情况，每月以货币形式支付乙方的工作报酬"；"甲乙双方按照国家及北京市的规定参加社会保险"，其它省市的聘用合同中关于工资和社保的约定也基本一致。由此可见，关于工资待遇与社保，学校与教师之间并没有可约定的空间。关于聘用合同解除条件的约定也是各区县的中小学也是直接使用省级政府制度的聘用合同模版。根据《**中小学教师违反职业道德行为处理办法**》规定，对于中小学教师作出的警告、记过、降低岗位等级或撤职、开除等处分，均有学校教育部门决定。

第二、因为聘用合同与学校签订，使得现实当中一些司法案例的解决，面临主体不确定性的问题。比如开除处分时，谁是被告的问题。第三、给县域内跨学校安排教师资源带来一系列的合法性危机。比如违背合同的相对性原则，阻碍了教师跨校间调配。改革的方面，应当以行政部门或学校。

本文认为中小学教师的聘用合同签订主体应由教育行政部门，另外，考虑到我国有些事业单位附属的中小学校，此类学校中小学教师的聘用合同由其举办者与中小学教师签订聘用合同。一方面可以使用合同双方是具有自主决定能力的主体，另一方面，也有利于解决实际的权利义务冲突，也有利于县级教育行政部门解决教师跨校统筹与分配的问题。

## 聘用合同的期限问题

中小学教师聘用制度改革，较之前的事业单位人事制度而言，较大的变化是中小学教师聘用合同有了一个确定的终止期限，即中小学教师与学校之间的人事关系不再是终身性质的。

《意见》规定：聘用合同分为短期、中长期和以完成一定工作为期限的合同。其中短期合同是指3年以下的聘用合同。

另外提出，"对在本单位工作已满25年或者在本单位连续工作已满10年且年龄距国家规定的退休年龄已不足10年的人员，提出订立聘用至退休的合同的，聘用单位应当与其订立聘用至该人员退休的合同"。

《事业单位人事管理条例》第十二条规定：事业单位与工作人员订立的聘用合同，期限一般不低于3年。

《事业单位人事管理条例》第十三条规定："初次就业的工作人员与事业单位订立的聘用合同期限3年以上的，试用期为12个月。"。

第十四条规定："事业单位工作人员在本单位连续工作满10年且距法定退休年龄不足10年，提出订立聘用至退休的合同的，事业单位应当与其订立聘用至退休的合同。"

该条规定对《意见》中的至退休合同的保留了第二种情况。该规定对于中小学教师而言，较为苛刻。按男教师法定退休年龄60计，也就意味着50岁之后才有可能提出订立至退休的合同，并不具体制度的合理性。因此，男教师50岁之前，和女教师45岁之前只能与学校签订固定期限的合同。

合同期限制度的本质功能在于，合同到期终止，合同双方之间的权利、义务灭失。当然双方可以协商续签合同，但是如果任何一方提出不续签，那么合同自然终止，另一方在法律上没有任何方式可以防止这一事件的发生，这对于保障教师的职业安全是十分不利的。这并不是危言耸听，在现实中已经存在，一些学校已经开始到期不续。比如北京丰台八中的案子。与此同时，教师在合同最初履行的时候，并不能到期自然终止，因为这有一个服务期的约定，比如合同期限是三年，但是有一个6年的服务期，服务期没有到期，聘用合同到期，教师则是不可以终止合同的。如何教师想终止合同，则要承担相应的违约责任。

### 聘用合同期限

应当至退休的聘用合同，第一、这符合我国中小学教师人事管理制度的事实，第二、保障教师职业安全和职业稳定性，吸引优秀人才从教的制度保障；第三、这也是世界各国公立中小学人事制度的共同做法。那么如何设定，本文认为可以规定可以借鉴劳动合同法无固定期限劳动合同的做法。第一个聘期结束之后，聘用主体同意续聘的话，除教师提出签定固定期限合同外，聘用主体应当与中小学教师签订至退休的聘用合同。固定期限合同不得超过5年。这样的制度设计一方面保障了教师的职业稳定性。另一方面，也给地方政府在教师初始时间期具有淘汰教师的自主权，且可以自主设定1到5年以内的考核时间周期。

### 服务期

服务期的这一概念的起源，约定服务期的前提条件是什么？服务期的约定
约定服务期的前提条件是教师享受政策性福利待遇，进而承担相应的服务期。《国务院批转国家计划委员会、国家教育委员会关于一九八五年全国高等学校毕业生分配问题报告的通知》（1985年）规定"实行定期服务制度。从一九八五年起，毕业生必须到分配的工作单位经见习合格后，连续服务五年，服务期满后允许合理流动"。最笔者能找到最早关于服务期的政策规定。这一政策的基础是当初的包分配制度，因为当时的高校毕业生、中专业生是培养是由政府来承担，服务期制度可以理解为是对政府培养成本的一种回报。服务是与培养制度是联系在一起的，比如公费师范生计划，也是存在服务期的规定，比如《国务院办公厅关于转发教育部等部门教育部直属师范大学师范生公费教育实施办法的通知》（国办发〔2018〕75号）中规定参与公费师范生教育学生毕业后有六年的服务期。
其**第十三条规定：**
公费师范生在协议规定服务期内，经省级教育行政部门同意，可在学校间流动或从事教育管理工作。可以说公费生制度中关于服务期的规定是学习之间的师范生培养制度。服务期的出现还有可能在招聘环节应聘者享受一些其它优惠或利益。比如《中共中央组织部、人力资源社会保障部关于进一步做好艰苦边远地区县乡事业单位公开招聘工作的通知》（人社部规〔2016〕3号）"对放宽条件招聘的人员，用人单位可以视情况在聘用合同中约定3-5年最低服务期限"。

基于以上规定，可以得出，服务期是指政府为劳动者提供一定资助或者优待的情况下，劳动者承诺在用人单位进行服务的期限。服务期是一种对等约定。另外，服务期是一种单方的义务设定。用人单位可以要求劳动者在本单位工作，但劳动者则不可以因服务期的存在而要求继续履行合同、或者续签合同。因此用人单位可以放弃服务期的要求。因此，服务期的约定的前提是经对方提供一定资助或政策优待。

因此，中小学教师聘用合同是否可以约定服务期，以及何种情况下可以约定服务期。因此，聘用合同可以约定服务期，但服务期关于期限的约定与用人单位提供的政策性待遇应当对等。违反服务期的约定可以约定承担相应的违约金。且违约金的数额与政策性的待遇为限，且按已经履行的服务期的时长同比例核减。服务期是否受聘用合同的期限制约，可以不用，因为合同期限对是对双方义务条款，而服务期是单方义务条款。因此可以并行实行。

引进人才人才政策性福利的问题，包括住房、非常规工资、住房、户口、补助性工资等。可以约定服务期？

## 聘用合同的终止问题

《意见》中规定的聘用合同必须具有的条款包括"聘用合同变更和终止的条件"，并没有规定可哪些条件可以终止。《事业单位人事管理条例》第十九条：自聘用合同依法解除、终止之日起，事业单位与被解除、终止聘用合同人员的人事关系终止。该条款规定的是合同终止的效力。合同终止的条件并没有做出规定。

合同终止的问题，聘用合同到期是终止的条件，那么，如果学校关闭停办。聘用合同是否终止的问题。依据合同的基本原理，聘用合同确立的权利义务关系由聘用合同双方承担，但如果一方主体消亡，那么合同的存续则已无意义，因此，学校停办是应当是聘用合同终止的条件之一。但是我国中小学教师人事管理的制度的实践则是在这种情况下，由政府部门另行安排其它学校。由此可知，教师人事关系的相对一方，不仅仅是学校，而且包括政府，政府是这种人事关系一项重要主体。从法律上如何解决这样一个矛盾，即将聘用合同的主体变更为行政部门，聘用合同由行政部门与教师签订，这样，教师工作所在的学校关闭，当然不能构成聘用合同关系终止的条件。但是还是一些其它条件符合时，聘用合同终止，其一，教师开始依法享受基本养老保险待遇的；其二，劳动者死亡，或者被人民法院宣告死亡或者宣告失踪的；

## 聘用合同解除权

固定期限合同到期终止，终止之前双作出双方关系灭失的决定。即是关系的解除。聘用合同的解决涉及到行政机关与或者学校与教师之间的权利义务关系问题。

人事关系作为，在一定情境下总会有终结的时候，这种关系的终止当然可以双方协议解决，总会有一方先提出，另一方是否同意的问题。在行政化的教师人事管理制度下，这体现为教师的辞职，和单位辞退两个方面。如何处理中小学教师离职的问题，因为中小学教师的事业单位工作人员属性，一直在执行人事部《全民所有制事业单位专业技术人员和管理人员辞职暂行规定》（人调发〔1990〕19号）[^1]、和《全民所有制事业单位辞退专业技术人员和管理人员暂行规定》（人调发〔1992〕18号），上述两部规定在2016年被废止[^2]，事业单位人事制度改革的基本方向，是实行聘用合同制，那么事业单位工作人员的离职问题，也就变成了聘用合同的解除与终止的问题。但是现有的关于聘用合同解除与终止的规定，零散而不系统。2002年《意见》的规定解除条件，一方面比较陈旧，和一些中小学教师人事管理实践不符，2014年《事业单位人事管理条例》对于聘用合同解除条件的规定是不完善的，并没有考虑到中小学教师人事管理的实际。因此，这需要进一步完善。完善的基本原则在参考公务员辞职和辞退规定的基本上，考虑中小学教师中小学教师管理的实际。

[^1]: 《关于执行〈全民所有制事业单位专业技术人员和管理人员辞职暂行规定〉中有关问题的通知》（人调发〔1991〕14号）

[^2]: 人力资源和社会保障部令（第28号）《人力资源社会保障部关于废止部分规章的决定》已经2016年4月5日人力资源社会保障部第93次部务会讨论通过。

**与此相反的我国公务员的辞职辞退规定，1995年《国家公务员辞职辞退暂行规定》，2009年**被《公务员辞去公职规定（试行）》、《公务员辞退规定（试行）》替代。**2020年《公务员辞去公职规定》**、**《公务员辞退规定》制定，因此，公务员辞职辞退有些完善的规定。**

事业单位的种类繁多，因此在《事业单位管理条例》只是将共性的解除条件进行了规定。但中小学教师人事管理有其特殊性，在适用《事业单位人事管理条例》的前提下，利用《教师法》修订的契机，应当根据中小学教师人事管理的特点，构建独立的聘用合同解除和相关制度。

### 协议解除权

聘用合同解除是指在聘用合同终止期限之前，经一方或双方意思表示，提前终止双方合同关系的行为。这涉及到双方协商解除和单方解除两种情况。《关于在事业单位试行人员聘用制度的意见》规定："聘用单位、受聘人员双方经协商一致，可以解除聘用合同"，但条例未做规定。如果是民事合同，法律应该遵循双方的意思自治，如果合同双方的自愿解除合同关系，法律当然允许。但中小学教师聘用合同的一方是行政机关，而且涉及公共利益，那么是否也允许双方协商解除？法律允许协商解除，即意味着，双方合同关系解除之后，双方都可以不用承担相应的法律后果。这就会产生一种情况：教育行政部门有选择性同意与一些教师解除聘用合同，而不与另一些教师解除聘用合同的可能，造成学校间、区域间解除聘用合同的差异，形成对教师解除聘用合同的差异对待。

协商解除的法律后果如何确定，一是关于服务期的约定，关于违约责任的约定，协商解除后，服务期是否是自动终止，违约责任是否应当承担？

因此，法律应当不允许，双方协商一致解除聘用合同。而只规定应当规定聘用合同单方解除的情形。一是中小学教师提出的单方解除的情况，一是用人单位单方解除聘用合同的情形，单方解除是指一方在符合法定的情形下，提出解除聘用合同，不以对方同意为前提，解除聘用合同的情形。

### 用人单位单方解除权

《事业单位人事管理》关于用人单位单方解除聘用合同的是其第第十五条、第十六条和第十八条，事业单位工作人员连续旷工超过15个工作日，或者1年内累计旷工超过30个工作日；事业单位工作人员年度考核不合格且不同意调整工作岗位，或者连续两年年度考核不合格的，事业单位提前30日书面通知，事业单位是可以单方解除合同的。另外，事业单位工作人员受到开除开除处分的，解除聘用合同。而《事业单位工作人员处分暂行规定》详细地规定可以给予事业单位工作人员开除处分的条件。因此，可以说，事业单位单方解除聘用合同时相对比较健全的。但是根据保护劳动者合法权益的需要，法律应当规定一定条件，用人单位不得单方解除聘用合同的条件，比如《公务员法》有相关的规定，《劳动合同法》亦有相关的规定，《意见》里也有相关的规定，但鉴于《意见》，需要在今天事业单位人事管理规定的一般法中明确这一点，也可以在教师法明确这一点。

### 教师单方解除权问题

《意见》规定：有下列情形之一的，受聘人员可以随时单方面解除聘用合同：（一）在试用期内的；（二）考入普通高等院校的；（三）被录用或者选调到国家机关工作的；（四）依法服兵役的。

第一项的合理性是试用期制度的必然要求。第四项是保障国家军队建议。但第（二）项在如果合理性存在的话，即是国家鼓励教师提高学历；这是没有正当性的。第（三）被录用或者选调到国家机关工作，机关工作用人。这是强调国家机关的工作要优先于教师的工作，这和国家教育优先发展的目标不相符合。

#### 预告解除权

《事业单位人事管理条例》第十七条："事业单位工作人员提前30日书面通知事业单位，可以解除聘用合同。但是，双方对解除聘用合同另有约定的除外。"。这个条款规定了合同约定的效力优先原则。因为中小学教师个体与学校或政府签订合同时处于不利的地位，让合同解决的条件由当事人双方协商，不利于对教师的保护。比如在学校会利用强调地位约定显著不公平的条款，而按现有的规定，承认其效力，显然是不适当的。现在中小学教师聘用合同的模型是根据《意见》中的规定制定的。《关于在事业单位试行人员聘用制度的意见》的规定是："受聘人员提出解除聘用合同未能与聘用单位协商一致的，受聘人员应当坚持正常工作，继续履行聘用合同；6个月后再次提出解除聘用合同仍未能与聘用单位协商一致的，即可单方面解除聘用合同。"，

因此，教师可以预告解除期是6个月。这个规定有可能是《规定》的第十七条是冲突，比如说，聘用合同有约定教师在首次提出解除聘用且学校不同意时，教师应当继续履行聘用合同，8个月后再次提出解除聘用合同未能与学校协商一致的，即可单方面解除聘用合同。照第十七条的规定，应当承认约定的效力。但这又是和《意见》的规定是冲突。作为国务院行政法规的《规定》的效力显然高于作为规范性文件的，那么考虑到中小学教师职业属性，6个月是否合适。

关于事业单位工作人员之间的关系解决的规定，最早的是

预告解除权是一种无理由的解除，在一定期限的情况下。适用《劳动合同法》的劳动者是有一个月的预告解除权的。《公务员》虽然没有预告无理由辞职，《公务员法》采取的规定除非法定不予审批的情况下，任免机关应当自接到公务员辞去公职申请之日起30日内予以审批，其中，对领导成员辞去公职的申请，应当自接到申请之日起90日内予以审批。因此，即使公务人员，其离职的权益在不损害公益利益的情况下，也是允许。那么显然教师也应当拥有这种预告解除权，但是考虑教师工作的特点，应当对于这种预告解除权进行一定限制。因为中小学教师工资都是以学期进行，可以规定，中小学教师解除合同的约定必须提前6个月提出。

#### 即时解除权

劳动合同法中规定了劳动者在用人单位出现过错时允许，劳动者可以立即解除劳动合同的权利，比如未按照劳动合同约定提供劳动保护或者劳动条件的；未请及时足额支付劳动报酬的，未依法为劳动者缴纳社会保险的。这种制定设计当然是基于保护劳动者的合法权益，同时督促用人单位履行法定或约定义务。那么聘用合同是否需要规定同时的条款。《公务员辞去公职规定》中并没有规定相应条款。基于保护中小学教师合法权益出发，当然也应当赋予中小学教师相关的即时解除权，但是中小学教师的工作是一项公共事业，在保护其权利时，同样不能损害公共利益。因此，在预告解除权制度下，即时解除权可以受到一定的限缩。但不排除，如果出现大量侵犯劳动权的情况下，可以立法赋予其自动解除权。当然，现在的条件下，可能这样规定还不现实。

### 解除的程序的问题

教师提出的应该书面告知，这个可以将自由裁量权交给学校，学校立即同意的。双方确定合同解除后，双方都有一定义务，保证双方的合法权益，中小学教师有义务完成工作交接手续。而用人单位应当中小学教师办理人事档案相关手续。

合同解除时，用人单位应当出具证明，并协助办理相关手续。

"履行聘用合同"指的是履行聘用合同文本中明确约定的事项、根据聘用合同的条款可以确定使用某种具体规则的事项，

肖新然与北京市大兴区第五小学人事争议二审民事裁定书，北京市第二中级人民法院民事裁定书（2019）京02民终4989号

工作条件与工作岗位、和工资福利待遇等要素中是否存在可约定的内容，还是依据法律和政策的规定。

## 赔偿金的问题

赔偿金是违法解除或者终止合同的惩罚性赔偿，是指对违反法定义务后，或者强行解除合同后应该承担的赔偿义务。那么学校与政府之间是否也涉及这层关系？肯定是需要的，如果教师任意离开，不履行任何交接的义务和提前通知的义务，但也不能强制其回来，但还是要承担一定的责任。这个惩罚性的责任如何确定？

相反，如果学校恣意解除与教师的人事关系，那么学校应该承担何种责任？

## 补偿金的问题

补偿金的性质？为什么聘用合同也要设计补偿金？应当参照《公务员法》和《劳动合同法》设定补偿金的条件。《公务员法》和《劳动合同法》都规定公务员或者劳动者可以获得补偿金的法定条件。那么在教师与政府或学校之间的法律关系终止或解除的情况下，在部分条件具备时，应当赋予教师补偿金的请求权，这一请求权在《意见》中已有规定，但是并不完善。比如说合同终止是否是可以请求补偿金的条件。当然应当是。

## 违约金问题

中小学教师聘用合同中是否可以约定金，何种条件下可以约定违约金？违约金的数额是多少？这是中小学教师聘用合同尚未解除的问题。《意见》和《规定》对违约金的规定并不明确。

《意见》第四条规定聘用合同的内容包括"违反聘用合同的责任"，但责任形式是否包括违约金，并不明确。
