---
title: "说说中小学教师教龄津贴的由来与未来"
author: "yy"
date: '2022-04-16'
output: html_document
---

**编者按：**中小学教师的"教龄津贴"是一个特别刺眼的存在，虽然是特定历史时期的制度残留，但如果使用得当的话，很可能成为改革中小学教师工资制度的一个重要抓手。

2022年4月2日教育部等八部门联合印发《新时代基础教育强师计划》，其中提到"提高教龄津贴标准"。对于中小学教师而言，"教龄津贴"是一个特别刺眼的存在，这是中小学教师工资结构的一个特殊科目，刺眼的原因在于，其只有3元、5元、7元和10元四个档次。在如今的工资水平下，还有一个如此数额的工资科目，不得不说是一件很可笑的事情。但最初实施时，教龄津贴还是一个很积极的政策。

中小学教师教龄津贴确定于1985年的国家机关、事业单位工作人员工资制度改革，这是1949年以来的四次工资制度改革的第二次（想了解中小学教师工资的四次改革，请参看[说说中小学教师的国标工资和10%增额](http://mp.weixin.qq.com/s?__biz=Mzg4MzIwOTEyOQ==&mid=2247483672&idx=1&sn=534bac242407c65ed2fe3b9cf44eb93c&chksm=cf4ba7def83c2ec8f43d0e1db30c8fba827b343ba38bd43b0ab98b20a9f34b112bcedb98d8be&scene=21#wechat_redirect)）。这次改革建立了以职务工资为主要内容的结构工资制。国家机关与事业单位工作工作人员实行统一的工资制度，其分开是1993年第三次工资改革完成的。当时统一的工资结构包括：基础工资、职务工资、工龄津贴、奖励工资。基础工资是以大体维持工作人员本人的基本生活费计算的，当时六类工资区定为40元，从领导干部到一般工作人员，均执行相同的基础工资。

职务工资是和中小学教师职务挂钩的（中小学教师职务工资标准见下图右侧）。1986年中小学教师职称制度的建立即是与结构工资改革进行配套的，职称在当时是指"职务名称"的简称。工龄津贴按照工作人员的工作年限逐年增长，每工作一年每月发给5角。奖励工资，用于奖励在工作中做出显著成绩的工作人员，有较大贡献的可以多奖，不平均发放。

在这次工资制度改革中，对于中小学教师、护士有一个特别规定。即是下面的条款：

> "为了鼓励中、小学校和中等专业学校、技工学校的教师、幼儿教师和护士长期从事本职业，除按规定发给工龄津贴外，另外分别加发教龄津贴和护士工龄津贴。教龄津贴和护士工龄津贴。教龄津贴和护士工龄津贴，均按从事本职工作的年限计算。从事本职工作满五年不满十年的，每月发三元；满十年不满十五年的，每月发五元；满十五年满二十年的，每月发七元；满二十年以上的，每月发十元。"

为落实教龄津贴制度，国务院工资制度改革小组、劳动人事部还专门发布了一个文件《关于教师教龄津贴的若干规定》。是谁提出设立教龄津贴的建议，缺乏文献材料，无法确切知道，只能揣测似乎和下面这位领导人的批示有关。

如果以当时的工资水平来衡量的话，教龄津贴的水平还是不错的。比如，对于新入职的小学教师，其职务工资是33元，基础工资是40元，新教师没有工龄工资，不算奖金的话，新教师第一年的月工资也就73元。因此，3、5、7、10元还算不错的。如果工作20年以上，一年可以拿120元，这比一个新教师的第一月工资还高一些。

从1985年制定教龄津贴的背景来看，教龄津贴其实是鼓励教师长期从教的特殊项目，并不是教师工资结构的常规项目，教龄津贴虽然与教师的工作经验有关，但其主要目的不是为对教师的工作经验进行激励。因为和教师工作经验直接对应的科目是工龄津贴。

教龄津贴标准从制定到现在一直没有调整过，而且在1993年和2006年的事业单位工资制度改革过程中，虽然中小学教师工资结构发生了很大的变化，但教龄津贴这一项目一直保留着。现在正在实施的岗位绩效工资制中，薪级工资在核定时是在一定程度上考虑工龄，但是工龄的权重并不是太高。

中小学教师这个职业是一个经验累积性的工作，且教师的工作质量有一些很难测量的部分，所以世界上很多国家都会将教师的工作年限作为教师工资水平的重要影响因子。而现在我国中小学教师的工资水平的决定因素中，职称扮演了过于重要的份量。

是否需要以及怎样提高教龄津贴？如果从调整中小学教师工资的结构来讲，应当提高中小学教师教龄的决定性作用，教龄津贴则是实现这一目标的手段。如果从调整中小学教师的工资水平来讲，因为教龄津贴，除了护士之外，是中小学教师工资结构中特有的一个科目，如果想单独提高中小学教师工资水平的话，教龄津贴也是一个比较好的政策手段。

在国家政策中明确提出提高中小学教师教龄津贴标准之前，河南省于2019年7月1日起，已经提高了中小学教师教龄津贴标准：在落实国家规定标准基础上，按照每增加一年教龄增加10元的标准累计计算核定。对于一个工作20年的教师而言，月工资可增加210元，也至少算得上是一个有意义的数字。

虽然《新时代基础教育强师计划》已经提出提高教龄津贴标准，但这一政策如何落地，还存在很大困难。因为中小学教师工资是由县级财政资金承担，增加教龄津贴，也就意味着增加县级财政支出。县级财政是否有这个财力和意愿，以中央政府是否有专项财政转移支付政策配套，是该政策是否落地的决定因素。如果没有国家层面的转移支付或者国家层面的标准的话，地方政府很可能选择性执行或者象征性地执行。
