---
title: "teacher_salary"
author: "yy"
date: "6/2/2021"
output: html_document
---

中小学教师工资争议纠纷的类型与司法处理
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 工资待遇争议的类型


## 哪些工资待遇争议类型

## 关于标准的问题

## 关于核定的问题

## 关于发放的问题
与中小学教师工资另外一个相关的主题，是根据不同政府确定的规则，确定每一位教师工资数额的问题。虽然涉及到则是确定之后的工资项目和数量是否按时足额发放的问题。那么中小学教师对工资待遇不满可能会涉及三个类型的问题，对中央、省、县确定的工资科目、标准和规则不满，对学校或者县行政部门根据上述规则确定的工资科目和数额不满，对已经确定的工资额度未能及时足额发放不满。

对于工资标准的确定问题是不具有可诉性的。 对于按照确定的规则工资认定的过程的不公正的问题？是可诉的，比如薪级工资的等级，绩效工资的等级与层次？ 对于按照确定的标准，认定的具体数额的工资示能按时额发放问题，是否可以提出诉讼的问题，这个是可以的，如果可以提出诉讼，那么诉讼的被告是谁？工资在现有的政策标准下确定结果与发放的问题，在司法实践中已经开始受理一些此类的案件，比如，秦海艳与武汉市第十六中学劳动争议案（2014）鄂江岸民初字第02325号，校内绩效工资的发放法院人事争议案进行了受理。[黄斌诉上海市松江区佘山学校人事争议案(2014)松民一(民)初字第3505]，关于奖励性绩效工作确定与发放的纠纷法院受理的案子，还有[张扣成与上海市三好中学劳动合同纠纷案，（2014）沪二中民三（民）终字第1005号]

法院认为教师请假期间的津补贴发放的问题不属于"辞职、辞退和履行聘用合同"相关的争议，不属于法院受理范围。[安远县岽坑学校、欧阳永强人事争议二审民事裁定书，（2018）赣07民终1551号]。有些法院认为奖励性绩效工资未出现聘用合同之中，而不属于人民法院事业单位人事争议案件的审理范围。（李海峰与如东县马塘小学人事争议二审民事裁定书2015）通中民终字第00480号，要求事业单位马塘小学支付其2013年年度奖励性绩效工资，因为双方没有签订聘用合同。

对于教师认为县工资低于其它地区教师工资，县级人民政府未执行上级政策政策为由提供的诉讼，最高人民法院认为"该诉请内容受政策调整"，不属于人民法院行政诉讼受案范围。教师工资结构中，根据不同省份的政策，可能存在还省级政府确定的津补贴科目，该科目的发放与否的问题。法院也认为"省标补贴发放问题是属于行政机关管理的范围"，不属于人民法院受理民事诉讼的受案范围。[冯文标与盐城市亭湖区新兴镇人民政府、盐城市亭湖区人民政府人事争议二审民事裁定书，（2015）盐民终字第00590号]

因此诸多关于工资待遇纠纷无法进入司法领域（王婉丽等诉齐齐哈尔市富拉尔基区教育局侵权纠纷案，(2017)黑民申33号），很多教师采取的非常规的方式。对于标准，比如说国家确定的国标工资的问题，对省级政策确定的津补贴的问题，以及县级绩效工资总额的问题。这些都不是现有的司法体系能够解决的问题。他们本身是一个政策性的问题。那么，也还会涉及不能同级政府的之间的财政分权的问题。中小学教师工资标准的问题是政策性的问题，在国外的解决方式，议案影响机制，与教师工会的协商机制。还可能是违宪审查机制。那么我们国家采取哪种机制让教师群体的声音能够得到表达，进而形成制约能力。 城镇学校教师支援乡村学校期间工资待遇的确定问题。因为为涉及到教育局的一个决定行为。法院将该争议纳入行政诉讼的范围。

但这一问题得不到解决所直接影响的群体是谁，首先是教师，中小学教师的劳动成果是否得到国家的认可与承认的问题，其次影响的是学生。如果中小学教师的劳动成果并不能得到认可，最终优秀的人才就不是选择这个职业，最终影响着教育质量，影响着个体的成长和成材。基础教育整体供应不足或质量带来的可能更广泛的社会和经济的发展问题。政府应当代表的保障质量的教育供给责任，但这个是有成本的。所以政府的内生动力在哪？在地方政策内生动力不足的情况下，中央政府如何调控与监督。另外，如何作为直接利益受损方的老师和学生家长，在国家、省县市的政策制定中以表达的诉讼的和相应的制约机制，这是政策研究者所必须思考的问题，通过议会，能过集体谈判。那么我们可依据什么呢？


中小学招聘过程中的引进人才专项费用的相关约定[钱锋与北京亦庄实验小学人事争议，（2020）京02民终2475号]，服务期约定的效力与违约期约定条款。

艰苦边远地区津贴主要是根据自然地理环境、社会发展等方面的差异，对在艰苦边远地区工作生活的工作人员给予适当补偿。特殊岗位津贴补贴主要体现对事业单位苦、脏、累、险及其他特殊岗位工作人员的政策倾斜。
