---
title: "teacher_ranks"
author: "yy"
date: "12/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 中小学教师职称评审的法律性质及其司法救济

## 引言

中小学教师职称是联结教师评价与教师工资之间的中间要素，涉及中小学教师重大切身利益。近些年来，中小学教师职称评审争议频频诉诸法院，而法院却以种种原因将其拒之门外，比如，法院认为职称评审是"内部行政行为"[^1]或者"内部管理行为"[^2]，不属于行政诉讼的受案范围；或者认为职称评审涉及对申请者专业技术能力的判断，是学术性的判断，应当尊重专家判断，排除司法审查[^3]；或者因被告不适格而被驳回起诉，因职称评审需经过学校、职称评审委员会、不同层级政府的教育行政部门或人社部门，比如，高级职称评审按规定由省人社部门组织评审，市人社部门公布结果，原告起诉市人社部门，被驳回起诉[^4]；再比如，市人社局委托教育局组建职称评审委员会评审，教师起诉教育局，被驳回起诉[^5]。与此同时，中小学教师职称评审腐败则屡禁不止，由司法判决文书可知，职称评审腐败牵涉职称评审中的各类主体：校长[^6]、评审委员会委员[^7]、教育局工作人员[^8]和人社局工作人员[^9]。虽然这些职务犯罪者受到了法律的应有制裁，但权益受损的教师如何救济则是一个急待解决的问题。以上问题都涉及对中小学教师职称评审的法律性质的判断及其是否应当纳入司法审查的问题。本文从分析中小学教师职称的本质属性入手，论证中小学教师职称评审的法律性质，并阐述将其纳入司法审查的必要性和可行性，最后从司法的角度提出完善中小学教师职称制度的若干建议。

[^1]: 杨述全诉铁岭市教育局履行法定职责案，辽宁省铁岭市中级人民法院行政裁定书(2015)铁立行终字第00006号。

[^2]: 吴明霞诉福建省教育厅教育行政管理(教育)案，福建省福州市中级人民法院行政裁定书(2019)闽01行终298号。

[^3]: 田益民与衢州市衢江区教育局履行教师职称评审职责案，浙江省高级人民法院行政裁定书(2015)浙立行申字第48号。

[^4]: 薛应光与毕节市人民政府行政复议案，贵州省高级人民法院行政判决书(2016)黔行终1143号。

[^5]: 王微微与哈尔滨市人民政府行政复议案，黑龙江省高级人民法院行政判决书(2019)黑行终154号。

[^6]: 庄晚辉受贿案，福建省惠安县人民法院刑事判决书(2017)闽0521刑初11号；王旭阳受贿罪案，河南省唐河县人民法院刑事判决书(2012)唐刑初字第349号。

[^7]: 刘海军受贿案，鹤壁市山城区人民法院刑事判决书(2013)山刑初字第138号。

[^8]: 杨德厚受贿案，云南省曲靖市中级人民法院刑事判决书(2014)曲中刑终字第21号；朱建明受贿案，浙江省缙云县人民法院刑事判决书(2021)浙1122刑初250号。

[^9]: 黄某某受贿案，周口市川汇区人民法院刑事判决书(2017)豫1602刑初793号。

## 中小学教师职称的本质属性

作为一个日常用词，人们对于"职称"的确切所指似乎并没有什么疑问，但政策文本中"职称"、"职务"、"专业技术资格"经常被等同使用，却使人感到困惑[^10]，职称到底是什么？职称与职务之间的联系是什么？回答这些问题，需要回顾中小学教师职称制度的历史沿革。

[^10]: 比较有代表性文件，如，2012年《吉林省专业技术资格（职务）评审工作规范（暂行）》中有表述："为进一步规范全省专业技术人员专业技术资格（职务）（以下简称职称）评审工作"。2015年，人力资源社会保障部教育部关于印发《关于深化中小学教师职称制度改革的指导意见》的通知中也是将"职称"与"职务"并行使用。

### 中小学教师职称制度的沿革

中小学教师职称制度是1986年由高等学校的职称制度承袭而来。职称一词最初是"职务名称"的简化[^11]，比如，1960年《国务院关于高等学校教师职务名称及其确定与提升办法的暂行规定》中的表述即是"高等学校教师职务名称定为：教授、副教授、讲师、助教四级"，这反映了当时干部人事管理的基本思想，即对高校教师的管理与行政机关工作人员一样，设定不同等级职务及相应名称，职务是指组织内具有特定职权和职责的岗位。1978年高校恢复职称评定时，继续沿用1960年文件[^12]。这时期，职称制度被扩散到其它职业当中，1979年国务院批转了若干业务技术职称暂行规定，比如《编辑干部业务职称暂行规定》、《新闻记者业务职称暂行规定》、《会计干部技术职称暂行规定》，出现诸如"业务职称"、"技术职称"的表述，是为了区分行政管理职务名称与专业技术岗位职务名称。这时期职称在运行中也由描述岗位的概念逐渐演化为一种属人化的概念，即职称成了附属于个体的"称号"。1981年《国家人事局关于贯彻执行国务院颁发的七种业务技术职称暂行规定若干问题的说明》指出："业务技术职称是反映专业干部的学识水平、业务能力和工作成就的称号"。作为一种称号的职称以学术、技术水平为评判依据， 没有数量限制，一旦授予， 终身享有。因相关制度不健全和缺乏经验，改革开放初期的职称评审工作出现标准不一，参评范围扩大，与工资待遇不当联结等问题。1983年，中央书记处、国务院决定暂停全国职称评定工作，并成立中央职称评定工作领导小组[^13]，统一领导全国的职称制度改革工作。

[^11]: 滕藤.齐心协力,共同搞好专业技术职务聘任工作[J].人才研究,1986,(04):1-3.

[^12]: 参见国务院批转《教育部关于高等学校恢复和提升教师职务问题的请示报告》（国发（1978）32号），1982年《教育部印发关于当前执行国务院关于高等学校教师职务名称及其确定与提升办法的暂行规定的实施意见》（（82）教干字003号）。

[^13]: 1985年，中央职称评定工作领导小组改为"中央职称改革工作领导小组"。

为改革职称评定工作中突出职称的称号性质，与岗位职责分离的问题[^14]，国家决定实施专业技术职务聘任制，其基本内容为：单位根据实际需要设定工作岗位，明确岗位职责和任职条件；在定编定员的的基础上，确定职务结构比例；由行政领导在经评定的专业技术人员中聘任；有一定的任期，在任职期间领取专业技术职务工资。实行专业技术职务聘任制的基础在于强调职称的岗位属性，1986年国务院发布的《关于实行专业技术职务聘任制度的规定》明确规定："专业技术职务是根据实际工作需要设置的，有明确职责、任职条件和任期，并需要具备专门的业务知识和技术水平才能担负的工作岗位，不同于一次获得后而终身拥有的学位、学衔等各种学术、技术称号"。专业技术职务是工作岗位，"聘任"是指将专业技术人员安排到相应专业技术职务相对应的岗位。专业技术人员在被聘任之前，需经一个评定的过程，这是后来实行"评聘分离"的基础，即职称可先评定，没有岗位时不聘任，有岗才聘任。按照当初的政策设想，把职称定义为工作岗位，职称工资意味着岗位工资，有利于贯彻按劳分配原则；职称是工作岗位，则可上可下，可长可短，有利于打破终身制，促进人才合理流动；也因为职称是工作岗位，根据单位工作需要控制岗位数量而控制职称数量就有了正当性。

[^14]: ［**中共中央、国务院转发《关于改革职称评定、实行专业技术职务聘任制度的报告》的通知**中发［1986］3号

《国务院关于实行专业技术职务聘任制度的规定》首次提出了"专业技术职务"和"专业技术职务系列"的概念。原国家教育委员会在此背景下制定了《中学教师职务试行条例》、《小学教师职务试行条例》、《关于中小学教师职务试行条例的实施意见》，正式开始实行中小学教师专业技术职务聘任制[^15]，作为专业技术职务系列之一。为落实中小学教师职称的岗位属性，《中学教师职务试行条例》和《小学教师职务试行条例》规定了各职称教师的岗位职责。确定职称的岗位属性之后，对于中小学教师而言，职称很自然地就成了从事该岗位的一种资格，比如，1994年人事部印发的《专业技术资格评定试行办法》将专业技术资格等同于"职称"[^16]，还指出"专业技术资格是学术技术水平的标志，一般没有岗位、数量的限制，不与工资等待遇挂钩，可作为聘任专业技术职务的依据"。职称作为一种岗位的定位也影响了后来教育法中关于职称的表述，比如，1993年制定的《教师法》和1995年制定的《教育法》均在规定中使用教师职务这一概念，2006年修订的《义务教育法》也是使用职务指代指称[^17]。中小学教师职称制度从建立起一直比较稳定，及至2009年开始试点、2015年全面推行对中小学教师职称制度进行改革，统一了中学教师职称、小学教师职称为一个系列，增加正高级职称。虽然依然坚持中小学教师职称评审是岗位聘用的重要依据，岗位聘用是职称评审结果的主要体现，即强调职称的岗位属性，但已经关注职称的属人化的一面，将职称评审定义为对中小学教师专业技术水平的一种认定，是教师评价工作的一部分。这次改革还要求中小学教师职称评审在核定的岗位结构比例内进行，不再实行"评聘分离"政策。

[^15]: 1983年《国家教育委员会关于中、小学教师队伍调整整顿和加强管理的意见》首先提到在中小学教师实行职称制度的设想。中小学教师职称制度实行之初，实行的是任命制，后来逐渐改成聘任制，二者的区别在于实行聘任制的学校，由校长或县以上教育行政部门领导向被聘任的教师发聘书，双方签订聘约；实行任命制的学校，由校长或县以上教育行政部门领导向被任命的教师发任命书。

[^16]: 比如，该文件有如下表述："保证客观、公正、准确地评定科技人员的中、高级专业技术资格（即职称，下同）"。

[^17]: 《教师法》第十六条规定："国家实行教师职务制度，具体办法由国务院规定"。《教育法》第三十五条第二款规定："学校及其他教育机构中的教学辅助人员和其他专业技术人员，实行专业技术职务聘任制度"。 《义务教育法》第三十条第二款规定："国家建立统一的义务教育教师职务制度。教师职务分为初级职务、中级职务和高级职务。"

### 中小学教师职称的本质属性

综述所述，可以发现中小学教师职称有两种可能的属性，一是指中小学校根据工作需要设置的具有特定职责、任职条件和任期的工作岗位，一是指证明中小学教师专业技术水平的称号。职称作为一种的制度设计，赋予其哪一种内涵，要看哪种定性更有助于实现特定的政策目标。基于功能的考虑，职称应当定义为一种专业技术水平的标志或称号，淡化其工作岗位属性，因为强调职称的岗位属性所预期达到的目标没有实现，相反还产生一些问题，而强调职称的称号属性，更符合实践中人们对于职称的认知，也有助于发挥职称制度应有的功能。

首先，中小学教师职称在实践中基本上是一次获得而终身拥有的称号，除非受到处分被撤销，最初通过聘期制度，促进教师流动的目标并没有实现。其次，岗位责任制的目标也没有实现。工资与岗位职责挂钩是合理的，但将职称定义为一种岗位，将职称与工资挂钩则是不合理的。大多数中小学教师的工作几乎没有岗位内容的差异，无法按工作量和工作性质设定不同岗位，教师晋升一级职称后，其工作内容很少发生变化，将职称的变化定义为岗位的变化是很件荒唐的事。更有甚者，因职称与工资挂钩，只要评上高级职称，可以干更少的活，依然可以拿更高的工资。第三，通过控制岗位数量控制不同职称等级人数，某种意义来说，这个政策目标是达到了，但这一做法合理性应当受到质疑。岗位数额限定带来的结果是，相同专业技术水平的教师并不能获得相同等级的职称，而职称制度又与工资制度强关联，意味着相同专业技术水平的教师并不能获得相同的激励，产生不公平。总而言之，将职称定义为一种岗位的政策功能有限。

将职称定义为专业技术水平的标志是促进教师职业成长的重要手段。对教师工作的激励包括两个方面：一个是能力提升，一个是努力程度。前者涉及工作质量，后者涉及工作量。职称制度解决的是工作质量的问题。做相同的工作，付出相同努力的情况下，能力水平越高的教师，工作质量越高。职称与工资挂钩的合理性在于其与教师潜在的工作质量相关。但职称解决不了如何激励教师做更多工作的问题。另外，将职称定义为一种专业技术水平的标志，并不必然会带来高级职称的膨胀。可以通过把控职称评审标准控制职称等级的合理结构，也可以通过对评定职称所需工作年限的设定，把职称结构控制在合理水平。不同职称等级的分布应当取决于区域内教师业务技术水平的分布。职称制度要做到相同标准的人获得相同的职称，这才能保证公平，才能给予教师稳定的职业预期。指标限额导致相同水平或者更高水平的教师评不上相应的职称，显然不利于实现职称的激励功能。

中小学教师职称晋升时考核评价的内容与标准也是决定职称本质属性重要因素。根据人力资源社会保障部教育部公布的《中小学教师水平评价基本标准条件》（2015年）和各省中小学职称评审规定，职称评审的内容包括教师师德、教育教学能力、教育科研能力、资历、学历以及一些政策性要求，比如，城镇中小学教师要有1年以上在薄弱学校或农村学校任教经历。《职称评审管理暂行规定》（2019年）第二条规定："职称评审是按照评审标准和程序，对专业技术人才品德、能力、业绩的评议和认定"。由此可见，职称是反映中小学教师业技术能力水平的标志或者称号，经规定主体和程序认定后附属于教师的。2017年，中共中央办公厅、国务院办公厅印发《关于深化职称制度改革的意见》中明确指出："职称是专业技术人才学术技术水平和专业能力的主要标志"。

## 中小学教师职称评审的法律性质

描述确定职称的用语在不同时期有不同变化，先后的用词有"确定与提升"、"确定和晋升"、"评定"、"评审"[^18]，2009年《关于深化中小学教师职称制度改革试点的指导意见》使用中小学教师"职称评审"这一表述。确定职称评审的法律性质是决定职称评审纠纷是否可以进入司法审查的关键。在回答这个问题之前，需知晓职称评审过程与评审结果的使用。

[^18]: 如1960年《**国务院关于高等学校教师职务名称及其确定与提升办法的暂行规定**》中使用"确定与提升"，1980年《国务院批转编辑干部业务职称暂行规定的通知》提到"确定和晋升"，1981年《国家人事局关于贯彻执行国务院颁发的七种业务技术职称暂行规定若干问题的说明》开始使用"评定业务技术职称"。

### 中小学教师职称评审过程

根据现有规定，中小学教师职称评审一般经过以下环节：个人申请、学校推荐、专家评审、部门审核与公示、学校聘用等。首先，教师根据政策文件和学校规定，向学校提出申请。其次，教师所在学校对申请的教师进行全面考核，决定推荐人选，学校一般制定内部考核标准和程序，组建考核推荐领导小组。再次，由职称评审委员会根据申请人的材料，或采取面试、试讲等方式，综合评价申请人的品德、能力与业绩，决定申请人是否符合申请职称的相应标准。最后，由行政部门对评审委员会产生的结果审核，并公示最终名单。根据各省公布中小学教师职称评审办法，职称评审的组织工作实行分级管理。中小学教师职称分为三级、二级、一级、高级和正高级。中小学教师的正高级职称由省级教育行政部门或者人力资源和社会保障部门组织实施，教师申报、学校推荐和其它级别的职称评审一样，县（区）和市级人社部门和教育部门负责正高级职称的推荐及材料报送工作。中小学教师高级职称评审工作一般由设区的市级政府的人社部门和教育部门组织实施。中小学教师一、二、三级职称评审的组织工作在各省有一些差异，其中，一级职称的评审有些省在市级，有些省下放到省直管县，北京、上海的一级职称在区一级。二、三级职称一般放在区县，而北京市的二、三级职称评审工作由学校组织实施。

### 中小学教师职称的使用

职称对于中小学教师的价值是我们确定职称评审性质的另一重要前提。可以说，中小学教师职称制度建立起来，一直是中小学教师工资水平的决定性因素。职称制度之前，1956年中小学教师已开始执行职务等级工资制度，中学教师分10个工资等级，小学教师分11个工资等级，职务等级工资的评定由领导和群体相结合的方法确定，评定与提升教师的工资级别以思想政治条件和业务工作能力为主要依据，同时照顾资历和教龄[^19]。可以说，职务等级是中小学教师职称制度的雏形。1985年，国务院工资制度改革小组、劳动人事部发布了《中小学教职工工资制度改革实施方案》建立以职务工资为主要内容的结构工资制。结构工资由基础工资、职务工资、工龄津贴和奖励工资构成，作为主要部分的"职务工资"的直接决定因素，即是1986年建立的中小学教师专业技术职务。1993年事业单位工作人员工资制度改革建立专业技术职务等级工资制度，专业技术职务等级工资主要分为专业技术职务工资和津贴两部分，二者的比例控制在7：3。其中，专业技术职务等级工资由职称决定。2006年事业单位工作人员工资制度改革后，中小学教师实行的是岗位绩效工资制度，由岗位工资、薪级工资、绩效工资和津贴补贴组成。其中，岗位工资、薪级工资执行全国统一标准，岗位工资完全由职称等级决定，薪级工资计算起点由职称决定，绩效工资本来是为激励教师工作取得的绩效，由地方政府制定标准，但实际执行时，职称也成了绩效工资的主要决定因素。总之，可以说自职称制度实施以来，职称一直是作为中小学教师工资的决定因子在使用。

[^19]: 参见《国务院关于评定和提升全日制中小学教师工资级别的暂行规定》（1960年）。

### 中小学教师职称评审的法律性质

就法律性质而言，中小学教师职称评审是一种行政确认行为，因其符合行政确认行为的本质要求。行政确认是指"行政主体对既存的法律事实和法律关系进行审查、认定并宣示其法律效力的行政行为"[^20]。首先，在中小学教师职称评审中，行政部门是组织者和决定者。虽然职称评审委员会在职称评审过程中起到关键作用，但职称评审委员会并不是一个独立的主体，其执行评审工作是来自于它的组建单位的委托。《职称评审管理暂行规定》（2019年）第六条规定："职称评审委员会负责评议、认定专业技术人才学术技术水平和专业能力，对组建单位负责，受组建单位监督"。因此，职称评审委员会的组建单位应当对职称评审委员会的行为负责。中小学教师职称评审委员会的组建单位有两种可能：一是行政部门，另外一种可能是当二级、三级职称组织评审工作被交给学校实施时，学校是职称评审委员会的组建单位，但此时学校行使的权力是来自于行政部门的委托，且学校职称评审的结果也需要行政部门审核确认。在中小学阶段，教师职称评审并不属于学校自主权的范围。另外，需要说明的是，学校虽然在一级职称及以上的评审过程中有推荐的权力，但是学校的推荐权力是来自于行政部门的委托，学校并不是在独立行使职称评审权。其次，行政部门组织实施中小学教师职称评审工作是履行法定职权的行为。中小学教师职称制度是我国《教育法》《教师法》《义务教育法》确立的教师人事管理制度，并由政府通过规章《职称评审管理暂行规定》和一系列规范性文件保证其实施。再次，职称评审是通过确定的标准和程序对教师业务技术水平的考查、认定。其认定的结果对教师和学校具有拘束力，职称在教师工资水平上起到决定性作用，职称升级是教师工资增加的必经方式。职称评审是事关中小学教师重大权益的事项，即获取劳动报酬的事项。职称并不是教师可有可无的荣誉称号，是其职业发展的必经阶段。综上所述，中小学教师职称评审是行政机关或行政机关委托的组织对中小学教师既存的专业技术水平的审查与认定，认定的结果对教师工资水平有着决定性作用，具有行政确认行为的本质属性，属于一种行政确认行为。

[^20]: 胡建淼. 行政法学［M］. 法律出版社，2010：207.

## 中小学教师职称评审的司法救济

中小学教师职称评审是一项行政确认行为，根据行政诉讼法规定，当事人如果对评审结果不满，可以提起行政诉讼。除了上文的合法性论证之外，将职称评审工作纳入司法审查还有其必要性和可行性。

### 纳入司法审查的必要性

中小学教师职称评审涉及到行政权力和专家权力的自由裁量，在职称评审过程中滥用职称、徇私舞弊现象一直存在，涉及学校管理层、评审委员会专家、以及负责召集专家的教育行政部门，还有负责最终审核的人事综合管理部门。任何一个主体不公正行使职权，都会影响职称评审的结果。且校长、评审专家和行政部门的管理者也比较容易形成利益共同体，不利于普通教师的权益保护。允许将职称评审行为纳入行政诉讼的受案范围，将有利于监督以上权力的行使。《职称评审管理暂行规定》（2019年）将职称评审监督主体设定为人力资源社会保障行政部门和教育行政部门，忽略了中小学教师职称评审的特殊性，其它系列职称评审多数由单位完成，比如高校的职称评审，而中小学教师职称评审，教育行政部门和人社部门是重要的决定主体，由行政部门监督行政部门行使职权，有违正当程序原则。正是如此，教师申诉制度在解决职称评审争议方面的功能也有限。综上，迫切需要将中小学教师职称评审纳入到行政诉讼的受案范围当中，接受司法监督。

### 纳入司法审查的可行性

反对将职称评审纳入司法审查的一个重要原因是，认为职称评审涉及专业性、学术性判断，需要有专业人士才能胜任，法官并不具备这种能力。诚然，判断一个教师的教育教学能力水平是法官不能胜任的，但职称评审不仅只涉及专业判断的问题，职称评审是各评审主体依据法律和规章、规范性文件和校规对中小学教师教师的专业技术水平进行认定的过程。职称评审涉及权力的合法行使问题。司法对职称评审过程的审查可以分为两个方面：一者是程序性审理，比如，评审规则与结果是否公示、利益相关者是否回避等。一是实体条件的审理，比如，职称评审方案规定需要由班主任经历，有在薄弱学校或者乡村学校的经历，法院当然有能力审理这些条件是否符合，还比如，法院也可以审理职称评审相关证明材料的真伪问题，法院也可以审理校内评审规则与政府制定的标准条件之间是否冲突问题，如推荐委员会组织是否具有代表性、是否有一些恣意的要求等。以上问题都是法官可以独立判断的问题，因此，将中小学教师职称评审纳入司法审查是可行的。

### 司法审查特别注意的事项

被纳入行政诉讼的中小学教师职称评审行为，法院应当按照行政诉讼法的规定对其合法性审查，在此无庸赘述。但中小学教师职称评审有一些独特的情况，需要特别考虑，涉及被告的确定、审查限度和判决方式的选择等。关于被告的选择问题。其一，针对职称评审委员会做出的决定不满，应当以职称评审委员会组建单位或委托单位为被告。实践中，各省在组建中小学教师职称评审委员会时，操作不一，有的是人社部门组建，有的是教育行政部门组建，有的是二者共同组建，有的是人社部门委托教育行政部门组建，有的是政府部门委托学校组建。评审委员会的组建模式在同省不同级别的职称评审中也不统一。除行政部门委托学校组建评审委员会之外，当对评审委员会评审意见不服时，应当以其组建单位为被告提起诉讼。其二，教育行政部门或者人社部门在职称评审中对申请人的材料审核并做出决定时，此时当然是该决定主体是被告。其三，职称评审过程中，学校可能做出两类决定。一是当政府将某一级职称评审权下放给学校的时候，由学校组建评审委员会进行评审，此时学校行使的权力是来自于行政部门的委托，应当以委托为被告；二是当评审工作由行政部门组建的评审委员会实施时，学校承担审查推荐工作，如果教师对被学校作出的处理决定不满，亦应当以委托单位为被告。

关于司法审查的限度问题，法院在对职称评审审查的过程中，对于职称评审委员会关于中小学教师专业技术水平的判断，除有证据表明有徇私舞弊的情况存在，应当尊重评审委员会的专业判断，避免司法审查过度，在法官不具判断能力的问题上做出判断。

关于判决方式的选择问题。中小学教师职称评审行为具有周期性，并非依申请即时组织，一般一年一个周期，教师一旦在一轮评审中落选，需要等到第二年才有补救的机会。教师在职称评审中受到可能的违法决定一般是被取消参评资格或者不予认定申请的职称的决定。在这些情形下，如果法院撤销行政机关的处理决定，判断继续履行法定职权，则对教师的实际救济效果不大，因为行政部门不可能再单独为该教师组织新一轮职称评审。因此，为了补偿中小学教师的合法权益受到的损失，可以选择判决具体行政行为违法，为教师争取国家赔偿提供依据。虽然，教师可以在第二年评审中得到更公正的对待，但因评审主体的违法行为而错过一年的机会成本，应当给予补偿。

## 结语

中小学教师职称是教师评价制度的结果，又是教师工资制度的依据，对激励教师成长发挥重要作用。作为中小学教师专业技术能力的一种标志， 在教师工资结构中应当占据一定比例，这是对教师工作能力提高的一种肯定，也是构建教师职业阶梯的一个方面。但职称并不能指示职称评定之后的工作量和也不完全代表其工作质量，因此，不能过度放大职称在工资水平的作用，在决定教师工资水平时要提高绩效和工作量在工资结构中的作用。另外，职称与教师工资挂钩，也就是与政府的教育财政投入挂钩。通过控制高级职称数量控制财政支出是不合理的。职称制度饱受诟病的一个方面是限额的问题，因为限额即是控制财政支出。作为一种专业技术水平的标志，对职称进行限额是不合理的，对教师不公平，也不利于发挥职称的激励作用。

中小学教师职称制度还有许多改进的空间，但从司法审查的角度，有以下两点需要改进：其一，统一职称评审的主体。考虑到职称评审工作需要专业知识，应当将职称评审的决定权配置给教育行政部门，这与人社部门拥有职称评审工作的综合管理职能也不冲突，因职称评审相关的政策与规则仍然可以由人社部门决定。但评审的具体组织工作应当完全由教育行政部门行使，这才比较符合实际，实践中主要是教育行政部门在组织中小学职称评审工作，而后由人社部门确认，由人社部门确认是没有实际功能的程序。如果人社部门行使最终决定权的话，那么教师对结果不满，应当以人社部门为被告，但人社部门又不是具体组织的部门，如果以教育行政部门为被告的话，教育行政部门又不是法定的最终决定主体。这既增加行政成本，又对教师维权不利。另外，还有些地方保留职称改革领导小组办公室之类的组织，职改办是一个临时性的组织，考虑到职称评审已经常规化和制度化，早应当废止了，其相应职能应当由常设和固定的政府职能部门承担。其二，进一步完善职称评审的程序规定。职称评审规则应当细化且公开，这包括政府制定的职称评审规定，也包括学校内部的职称评审规定，如此，法官审理此类案件才有根据。此外，有效的监督主体来自于利益相关者的监督，职称评审结果向社会公开，利益相关者和與论监督才有可能。
