---
title: "中小学教师编制管理法制化研究（工作论文）"
author: "叶阳永"
date: "11/6/2020-05/13/2021"
output:
  workflowr::wflow_html:
    toc: true
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 引言

中小学教师编制涉及一定范围内（如省市县校）中小学教师数量与结构的核定与配置问题[^teacher_quotation-1]。中小学教师编制的现状与中小学教师编制管理的制度供给之间存在偏差。一方面，编制问题成为制约县域中小学校发展的重要因素。城镇大班额下的缺编缺人与农村小规模学校超编缺人并存；学校新增事务，比如寄宿制、营养餐项目等，缺少人力投入；教师参加培训或者休病假产假等产生的临时性用人需求得不到满足；还存在"在编不在岗"或者"有编不补"等问题（邬志辉，陈昌盛，2018；柳丽娜，朱家存，2009）。学者提出了一系列建议，比如，建立动态的编制调配机制（杨卫安，袁媛，2019），实行教师编制单列管理（刘善槐，朱秀红，李畇赟，2019；邬志辉，陈昌盛，2018），加强教师编制使用与管理的监督力度（杨卫安，袁媛，2019），根据教育教学工作量核定编制数（周兆海，邬志辉，2014）， 根据学校的临时性需要设置机动编制（邬志辉，陈昌盛，2018）或者附加编制（李宜江，2013），将编制资源在全县范围内跨学校统筹，甚至跨区县"市域调剂"（杨卫安，袁媛，2019）。另一方面，我国先后发布了四个中小学教师编制相关的文件：《教育部关于中等师范学校和全日制中小学教职工编制标准的意见》（[84]教计字239号），《国务院办公厅转发中央编办、教育部、财政部关于制定中小学教职工编制标准意见的通知》（国办发〔2001〕74号），《中央编办教育部财政部关于进一步落实〈国务院办公厅转发中央编办、教育部、财政部关于制定中小学教职工编制标准意见的通知〉有关问题的通知》（中央编办发〔2009〕6号）和《中央编办、教育部、财政部关于统一城乡中小学教职工编制标准的通知》（中央编办发〔2014〕72号）。分析这些文件可以发现，在确定常规中小学教师编制标准的基础上，都明确提出对规模较少或者教学点较多地区、寄宿制学校、存在病产假等情形下可适当增加编制，对在编不在岗和有编不补等违反编制管理规定的行为都做了严厉的禁止性规定，2009年和2014年文件都提出完善编制的动态调整机制。这些制度规定与上述关于中小学教师编制现状的研究结论存在偏差。为什么中央政策得不到有效执行？为什么中央规定适当增编的因素没有得到地方政府考虑？为什么在编不在岗和有编不补的现象依然存在？为什么编制动态调整得不到落实？本文认为中小学教师编制管理制度有效性差的原因在于中小学教师编制管理中存在制度性的障碍。编制在我国行政管理体制中承担多种功能，涉及不同层级政府及政府内部不同部门之间的复杂关系，缺乏对编制功能和编制管理体制的深入分析，已有研究未能剖析编制制度改革难以落地的制度性障碍，导致相应的制度设计有效性不足。本文将首先呈现中小学编制管理制度及其沿革过程，而后对编制功能进行阐释。在此基础上，分析导致编制问题迟迟不能解决的制度性障碍，进而提出实现中小学教师管理法制化的具体建议。

[^teacher_quotation-1]: 编制问题涉及到人员数额与领导职数两个方面，比如《地方各级人民政府机构设置和编制管理条例》（20074年）第二十八条规定"本条例所称编制，是指机构编制管理机关核定的行政机构和事业单位的人员数额和领导职数"，人员数额又涉及编制数额与编制结构，比如《江苏省事业单位机构编制管理办法》（2010年）第二十条规定"事业单位编制管理事项，包括编制员额、编制结构和领导职数的核定、调整"。因此，中小学教师编制涉及中小学教师数量与结构以及中小学校领导职数的问题。中小学学校领导职数涉及中小学校管理制度问题，为保证研究的针对性，本文只关注中小学教师编制问题中的教师的数量与结构问题。本文所称中小学教师是指中小学教职工，包括教师、职员、教学辅助人员和工勤人员。

## 中小学教师编制管理制度的沿革

编制分为行政编制和事业编制，中小学教师编制是事业编制的一种，事业编制管理制度和编制管理的综合性规定当然适用于中小学教师编制管理。中小学教师编制管理相关规定同时存在于中央和地方性的规定之中，下面将分别介绍。

### 事业编制管理的中央规定

1986年劳动人事部《关于加强事业单位编制管理的几项规定的通知》（劳人编〔1986〕273号）是我国较早的事业单位编制管理文件，其规定"地方国家机关所属事业单位人员编制的审定工作，在各省、自治区、直辖市人民政府领导下，由各地编制部门承担，劳动人事部负责业务指导"，中央国家机关各有关部门会同劳动人事部，对教育、科研、文化、卫生等各类事业单位，制定合理的人员编制标准，各省、自治区、直辖市和中央国家机关各部门以此为依据，结合本地区、本部门的适情况制定实施细则，而且提到了要实现编制管理法制化的目标。1996年中共中央办公厅国务院办公厅关于印发《中央机构编制委员会关于事业单位机构改革若干问题的意见》的通知（中办发〔1996〕17号）同样授权中央编制部门会同相关部门制定编制标准，省级编制部门制定本省事业单位编制管理办法，编制事宜按分级管理的原则与权限，由各级机构编制部门统一审批。同时提出对事业单位编制实行"制度化的总量控制"，加强事业单位编制法制建设。2002年《中共中央办公厅国务院办公厅关于进一步加强机构编制管理工作的通知》（厅字〔2002〕7号）强调了坚持编制工作的集中统一领导和分级管理。集中统一领导是指编制工作由机构编制委员会及其办公室统一负责，由机构编制专项法规规章和文件规定，禁止其它部门擅自决定，禁止其它文件作出编制相关的规定，禁止业务部门对下级业务部门编制管理的干预。分级管理是指中央机构编制委员会及其办公室和地方各级机构编制委员会及其办公室在其自各权限范围内负责编制的管理工作。

2007年国务院颁布属于行政法规的《地方各级人民政府机构设置和编制管理条例》，该条例规定地方的事业编制管理办法，由省、自治区、直辖市人民政府机构编制管理机关拟定，报国务院机构编制管理机关审核后，由省、自治区、直辖市人民政府发布。2013年，新一届政府承诺"财政供养人员只减不增"，事业编制总量以前由各省根据情况确定，2013之后被中央要求控制在2012年底事业单位编制总量以内。同时中央确定编制管理的基本原则是严控总量，盘活存量，优化结构，增减平衡。《中央编办关于印发创新事业单位机构编制管理方式意见的通知》（中央编办发〔2014〕73号）再次强调"在一定时期内将事业编制总量控制在 2012 年底统计数内，调剂出来的编制用于经济社会发展亟需的领域"。 特别提到对承担义务教育、公共卫生等面向社会提供公益服务的公益一类事业单位，建立和完善编制标准，严格控制总量。中央编办关于印发《关于地方事业编制挖潜创新服务发展的指导意见》的通知（中央编办发〔2017〕56号）主要是列举性规定可以使用的核减编制和创新管理的方式。

2018年，我国编制领导机构发生重大变化，中共中央印发的《深化党和国家机构改革方案》提出调整优化中央机构编制委员会领导体制，作为党中央决策议事协调机构，统筹负责党和国家机构职能编制工作。中央机构编制委员会办公室作为中央机构编制委员会的办事机构，承担中央机构编制委员会日常工作，归口中央组织部管理。改革前中央编委主任为国务院总理，中央机构编制委员会办公室是中共中央的工作部门，也是国务院的工作部门。2019年中共中央颁布《中国共产党机构编制工作条例》规定了机构编制领导体制和机构编制审核调整程序，事业单位编制管理适用该条例。地方各级党委设立机构编制委员会，管理本地区机构编制工作，各级机构编制委员会下设办公室，承担日常工作，归口本级党委组织部门管理，根据授权和规定程序处理机构编制具体事宜。中央及地方各级党委设立的机构编制管理委员会及其下设的办公室，构成了我国的编制领导体制。2019年，习近平总书记在中央机构编制委员会第一次会议上发表讲话，提出"严控总量、统筹使用、有减有增、动态平衡、保证重点、服务发展"的编制管理原则，强调编制的统筹使用和根据情况有减有增，不是一味的严格控制。

### 事业编制管理的地方规定

根据上文分析，我国编制领导体制是中央规定的，但事业编制管理制度主要是由地方性法规、规章或者规范性文件规定的，多数以地方政府规章形式规定的。较早的管理规定比如《甘肃省各级机构编制暂行管理办法》（1980年[^teacher_quotation-2]，2003年废止）、《四川省省级事业机构编制管理试行办法》（1984年）、《北京市机构编制管理暂行办法》（1985年，1998年废止）、《上海市政府机关和事业单位机构编制管理暂行规定》（1986年，2010年修订，2013年废止）。甘肃与北京的规定涉及中小学教师编制的规定较少，上海市的规定提到区、县所属事业单位编制数的确定或者调整，在市编制委员会确定的控制数内，由区、县编制委员会批准，报市编制委员会备案。

[^teacher_quotation-2]: 本文文件名称后括号内第1个数字指示该文件开始生效日期。

1990年左右，也是1986年劳动人事部《关于加强事业单位编制管理的几项规定的通知》颁布之后，地方政府制定了涉及事业编制管理的规定，比如《沈阳市事业单位编制管理暂行办法》（1987年，2002失效）、《四川省全民所有制事业单位机构编制管理试行办法》（1988年）、《安徽省事业单位机构编制管理暂行规定》（1989年）等[^teacher_quotation-3]。这一时期事业编制管理规定主要涉及事业编制的种类以及审批权限的分配。比如安徽省规定全日制中小学人员编制及内部机构设置由同级教育委员会会同同级编制部门审批。河南省事业编制规定有总量控制的表述。安徽、甘肃省的规定都提到各类事业单位的人员编制主要采取制定编制定员标准和规定各类人员比例的办法进行管理。《长春市事业单位机构编制管理规定》较早提到"编制部门对事业单位机构编制应根据其职责变化适时调整，实行动态管理"。整体而言，这一时期的事业编制管理规定较为简略。

[^teacher_quotation-3]: 其它还有《河南省事业单位编制管理暂行规定》（1989年）、《甘肃省事业机构编制管理暂行办法》（1990年，2018年失效）、《山西省事业机构编制暂行管理办法》（1990年）、《宁夏回族自治区事业机构编制管理办法》（1991年，2002年废止）、《江西省机构编制管理暂行规定》（1991年）、《长春市事业单位机构编制管理规定》（1992年，2020修改）。

2000年左右，地方政府又制定了一批事业编制管理相关的规定，比如《河南省事业单位机构编制管理规定》（1997年，2011年失效）、《黑龙江省事业单位机构编制管理规定》（1999年）等[^teacher_quotation-4]。这一时期除了具体化统一领导、分级管理原则之外，突出强调总量控制原则，青海、宁夏、山东、黑龙江明确提出总量控制原则。青海、重庆、黑龙江开始强调动态管理原则。2007年在《地方各级人民政府机构设置和编制管理条例》授权之下，地方政府开始新一轮事业编制管理规定的制定，比如属于地方性法规的《海南省各级国家机关、事业单位机构设置和编制管理条例》（2010年）、《云南省机构编制管理条例》（2008年），另外则以地方政府规章的形式制定的，如《宁夏回族自治区事业单位机构编制管理规定》（2008年）等[^teacher_quotation-5]。在查阅的云南、宁夏、安徽、江苏、河南、新疆、山东、海南、辽宁九省事业编制管理文件中，全部强调了总量控制原则。江苏、河南、新疆、山东、安徽、海南、辽宁提到动态调整原则，但多数省份仅是对动态调整的原则性表述，仅山东和安徽规定了编制调整的条件，比如，山东省规定事业单位职责任务发生变化的，事业单位编制标准调整的或者事业单位合并、分设的，编制部门可以调整事业单位编制。宁夏的规定较早提出"建立事业单位机构编制公开制度，接受社会监督"。

[^teacher_quotation-4]: 其它还有《重庆市事业单位机构编制管理办法》（2001年）、《宁夏回族自治区事业机构编制管理规定》（2002年，2008年失效）、《山东省事业单位机构编制管理规定》（2003年，2016年失效）、《青海省事业单位机构设置和编制管理暂行办法》（2003年）。

[^teacher_quotation-5]: 其它还有《安徽省事业单位机构设置和编制管理规定》（2009年，2014年）、《江苏省事业单位机构编制管理办法》（2010年）、《新疆维吾尔自治区事业单位机构编制管理办法》（2011年）、《河南省事业单位机构编制管理办法》（2011年）、《山东省事业单位机构编制管理规定》（2017年）、《无锡市事业单位机构编制管理办法》（2012年，2018年修订）、《甘肃省机构编制管理办法》（2009年，2019年废止），《山西省机构编制管理规定》（2008年）。

2019年《中国共产党机构编制工作条例》公布以后，部分省委开始制定省委机构编制管理规定，比如《中共河北省委机构编制管理规定》（2020年）、《四川省贯彻\<中国共产党机构编制工作条例\>实施办法》（2020年）、《江苏省贯彻\<中国共产党机构编制工作条例\>实施办法》（2020年）。2019年9月27日，辽宁省人民代表大会常务委员会废止了2018年02月01日开始实施的《辽宁省机构和编制管理条例》。省委机构编制管理规定主要是执行《中国共产党机构编制工作条例》的内容，比较大的内容变化是强调可根据情况变化对编制进行跨部门、跨地区调整。

### 中小学教师编制管理专项的地方性规定

为落实国家关于中小学教师编制管理的规定，地方制定了相应的实施办法。2001年中小学教师编制标准文件之前，地方性中小学编制文件有《安徽省全日制中小学机构编制管理暂行办法》（1999年）、《山东省全日制中小学职业中学机构编制管理暂行规定》（1999年）。2001年国家中小学教师编制标准公布以后，省级人民政府制定实施办法的有湖北、内蒙古、河南、海南、宁夏、重庆、黑龙江、新疆、青海等。省级中小学教师编制管理规定首先涉及的是编制标准，一方面直接使用中央的生师比标准，另一方面是对额外增加编制的情形进行了明确，比如海南的规定中学住校生每200名增加1名，小学住校生每150名增加1名编制；宁夏的规定综合各寄宿、教学点、脱产进修等情形，在以市、县(区)为单位按标准核定中小学教职工编制总额的基础上，另补充5％的附加编制；广西规定开设民族语文课程的教学班，每班可增加0.3名教师编制。其二，重申了中小学教师编制管理的基本规则，这包括：中小学教师编制标准及管理办法由省级编制部门会同财政部门与教育部门提出方案，报省级政府批准。区县市教育行政部门提出本区域的编制建议方案，编制部门会同财政部门研究，根据省级确定的编制标准，确定本县市编制标准，报省机构编制部门核批。辖区的市编制、教育、财政部门协助省编制、教育、财政部门做好逐县核定教师编制工作以及直属学校教职工编制的核定工作；区县教育行政部门在下达的编制总额内，具体核定本级各中小学的人员编制，并报同级机构编制部门备案。各级财政部门依据编制部门核定的人员编制，核拨中小学人员经费。其三，对中小学教师编制的动态调整也做了不同的规定，涉及县域内各中小学校的编制调整和区县中小学教师编制总量的调整两个方面。黑龙江、宁夏、内蒙古、河南的编制规定未提及动态调整，海南只是强调动态调整原则。山东、安徽、湖北规定了学校层面编制调整的时间，山东规定两年重新核定一次，安徽省强调"原则上每三年"核定一次，湖北规定每三年调整一次。关于区县中小学教师编制总量调整的问题，青海省规定"原则上第3至5年"调整一次，重庆规定"原则上每两年核批1次"。

## 中小学教师编制的功能分析

中小学教师编制是一种独特的制度设计，在学校教学工作安排、教师人事管理、层级政府财政责任分担和权力运行等方面发挥重要作用，只有理解编制在不同系统中承担的各种功能，才能系统地分析编制管理存在问题的原因，寻找解决问题的方案。

### 作为一种教育教学任务分解单位的编制

基础教育是一项重人力资源投入的行业。基础教育的举办者需要根据基础教育需求量确定所需的中小学教师数量。学生数量是基础教育需求量最主要的决定变量，现行常规中小学教职工编制标准的主要因素是学生数量，其规定高中教职工与学生比为1：12.5、初中为1：13.5、小学为1：19。当然学生数量并不是决定教育教学工作量的唯一变量，确定编制标准还需考虑班级大小、学校规模、地域特点等其它要素。尽管人们对编制数量的影响因素有不同考量，但在讨论编制标准时，编制是作为一种教育教学任务分解的基本单位存在的。科学合理的编制标准设计决定教育教学任务有效完成，关于中小学教师编制的研究很多是在这个层面进行的，通过评估学校教育教学需求，来评估学校编制的余缺（邬志辉，陈昌盛，2018；张宗倩，秦玉友，2020）。

### 作为一种政府人事管理手段的编制

中小学教师作为事业单位工作人员，其在聘任、工资待遇、社会保障、人事关系解除等方面的权利与义务由一系列适用于事业单位工作人员的人事制度确定。适用这些制度的前提是中小学教师被政府纳入编制内管理。讨论一个教师是否有编制，即是指该教师是否被纳入编制内管理。纳入编制内管理的教师的工资待遇、社会保障和职业稳定性由国家一系列的人事制度提供保障。编制管理制度一般情况下又与户口制度挂钩，纳入编制管理的人员可获得工作地户口，户口又和其它公共服务挂钩在一起，比如房屋买卖、汽车摇号、子女上学等。教师如果没有被纳入编制管理，则成为编外教师，这些制度性的保障与福利则不一定享有。说明这一差别的直接例证即是特岗教师制度。特岗教师在工作前三年是不入编的，其相关的权利义务关系以及享有的福利与正式在编的中小学教师是不一样的，只有经过三年服务期考核合格之后，才正式纳入编制管理。编制对于个体的意义，即是这种差别的权利义务配置。正是因为编制的存在，使得有编制内外的不同身份的教师，这一现象并不必然是一个问题，问题在于编外教师管理制度的不完善。

### 作为一种政府财政拨款单位的编制

基础教育是政府按照法律规定必须提供的基本公共服务。公共服务是有成本的，人力成本是基础教育成本的重要组成部分。对于纳入编制管理的中小学教师而言，有政府保障的工资标准和相应的福利待遇，纳入编制内管理的教师对于政府则意味着需要有相应的经费投入。从这个意义上而言，中小学教师编制是政府确定基础教育投入或者说确定财政拨款总额的基本单位。在工资待遇确定的情况下，编制数量越大，政府的财政投入就越大，编制数量越小，政府的财政投入就越小。政府对基础教育的人力投入是以编制为基本单位进行核算的，人力投入是基础教育成本最为主要的组成部分，某种意义上，教师编制数量反映着政府基础教育投入水平。

### 作为一种政府权力监督手段的编制

编制管理的一个重要原则是总量控制，即下级编制管理部门要在上级编制管理部门核定的事业编制总量和结构范围内对本区域的编制进行管理。就中小学教师编制而言，县级政府编制管理部门必须在上级政府确定的事业编制总量范围内确定各中小学校的编制。一般情况下，由省级编制管理机关在中央政策的指导下确定全省的事业编制总量，再将事业单位编制总量分配到市县区政府。为什么事业编制管理实行总量控制？主要是因为编制与财政投入挂钩，分配编制的权力即是分配财政资源的权力，编制核定权是极为重要的权力之一，没有强有力监督的话，容易被滥用，地方政府具有很强扩编动机，中共中央和国务院于1987年、1990年、1997年、2001年、2007年和2011年不断下发通知，强调严格控制机构编制[^teacher_quotation-6]，即说明了这一点。因此，编制总量控制实际上是一种权力监督的手段，是上级政府对下级政府人事权的控制与监督，防止下级政府滥用编制权力。因编制与财政投入之间的关系，编制也是上级政府对下级政府预算监督的重要手段。

[^teacher_quotation-6]: 文件包括《中共中央、国务院关于制止机构、编制和干部队伍膨胀的通知》(中发〔1987〕12号文件)、《国务院关于进一步加强机构编制管理的通知》(国发〔1990〕14号)、《中共中央办公厅、国务院办公厅关于加强管理防止机构编制再度膨胀的通知》（中办发〔1997〕7号文件）、《中共中央办公厅、国务院办公厅关于严格控制机构编制的通知》（厅字〔2001〕40号)、《中共中央办公厅、国务院办公厅关于进一步加强和完善机构编制管理严格控制机构编制的通知》(厅字〔2007〕2号)、《中共中央办公厅、国务院办公厅关于严格控制机构编制的通知》(厅字〔2011〕22号)。

## 中小学教师编制管理中的制度性障碍

### 教师人事管理的属校性限制了跨校流动

以校为单位的事业单位人事管理制度是编制管理中校际间结构性缺编问题的原因之一。其一、我国事业单位人事制度改革的方向是建立事业单位与其工作人员之间以聘用合同为基础的人事管理关系。《教师法》第十七条规定由学校和教师签订聘任合同，明确规定双方的权利、义务和责任。实践中教师也是与学校签订的聘用合同，与教师发生权利义务关系的对象是学校。其二、县教育行政部门也是根据学校为单位核定编制的，编制本身具有很强的学校属性。其三、人事管理中教师绩效工资核定、职称评审等制度也是以学校为单位分配的，虽然国家在推进"县管校聘"改革，但是该项改革仍在尝试之中，且《教师法》确定的聘用合同制度还无法突破。第四、聘用合同签订、绩效工资和职称评审是人事管理部门的职权，教师的跨校流动还涉及教育部门与人事部门之间的衔接问题。因此，跨校流动的人事管理成本影响了编制在县域内的跨校流动。

### 总量控制原则限制了地方政府的积极性

事业编制管理中的总量控制原则主要是解决权力监督的问题。在没有健全有力的同级政府公共财政支出监督的情况下，没有上级政府控制编制总量，下级政府会有很强的扩编冲动。但是这一原则却限制了地方政府根据地方实际需求变化调整编制总量的空间，正是由于受到事业单位总量控制的影响，再加上核定的总量不及时调整，地方政府新增的教育需求则得不到有效回应，尤其是对人口流入地政府而言，这一矛盾尤为严重。另外，因为编制总量与财政投入之间的关系，财力不足的区县，总量控制恰成了其压缩财政投入的挡箭牌；具有财力且有意愿加大基础教育投入的区县，当然也是基础教育的实际需求增加，如人口流入量比较大的地区，因为没有编制，不得不使用编外教师，因为编外教师相关制度不健全，产生"同工不同酬"等一系列问题。

### 中小学教师编制管理的附属性忽视了其独特性

虽然有中小学教师编制管理的专项文件，但其整体上受事业编制管理制度的约束。我国事业单位种类繁多，涉及教育、卫生、文化、科技、出版、勘探、农林水利等方面，不同领域有不同特点，承担的功能与相应管理制度也不相同。中小学编制附属于事业编制管理之中存在以下问题：第一、没有考虑到中小学教师这一职业和其承担的公共服务职能的特殊性，比如，事业编制监督管理制度的设计主要考虑行政编制管理的特点，行政编制与中小学教师编制对地方政府的影响的差别在于前者是一种重要的"政治资源和执政资源"，政府具有很强扩编冲动，后者则是一种义务，从减少财政支出的角度上讲，其动机是减少中小学教师的编制，这是中小学教师编制中存在有编不补问题的原因。第二、因为中小学教师编制是具有很强的义务属性，并不会像其它事业单位的人员扩充给行政部门带来职能分担的利好，在上级政府确定事业编制总量情况下，且事业编制在不同行业的分配规则不确定的情况下，教育行政部门在与其它行政部门争取编制数量时处于劣势地位。第三、事业编制管理实行的是集中统一领导，事业编制管理制度的调整必须有编制部门或者编制专门法规规章调整，这需要等各类事业单位的条件都成熟才能启动改革，这阻碍中小学教师编制管理制度的及时有效调整。

### 县级政府财政支出能力制约了编制增加

编制作为一种财政拨款的基本单位，编制数额决定政府财政投入水平，政府财力水平是制约编制供给的重要因素。2001年我国开始实行以县为主的政策，即中小学教师工资保障的责任主体是区县政府。之后建立了相应的转移支付制度，即中央人民政府或者省级人民政府根据区县政府财力下拨一定数量财政经费，多以一般性转移支付下拨，一般性转移支付可用于政府的各项支出，无法明确中小学教师的工资多少来自于上级政府的转移支付。2005年农村义务教育经费保障改革，2015年的完善城乡义务教育经费保障机制改革，针对的是公用经费、学生资助相关经费的中央与地方分担比例问题，没有涉及教师工资保障机制问题。2016年《国务院关于推进中央与地方财政事权和支出责任划分改革的指导意见》将义务教育划为中央与地方共同财政事权的事项，由中央与地方按比例或以中央为主承担支出责任。但2018年国务院办公厅下发的《基本公共服务领域中央与地方共同财政事权和支出责任划分改革方案》所列举的中央与地方共同财政事权范围内的关于义务教育的支出责任领域只涉及到公用经费和学生资助等项，并未包含中小学教师工资。2019年《国务院办公厅关于印发教育领域中央与地方财政事权和支出责任划分改革方案的通知》虽然提到了义务教育教师工资保障问题，但只是重申以县为主政策，并未明确在教师工资上中央和省市两级政府转移支付的责任和比例。县级政府是基础教育教师工资保障的责任主体，基础教育支出是县级人民政府财政支出的重要组成部分，基础教育投入具有外溢性强和收益周期长两大特点，县级政府的主政者主动投入教育的动力不足。因此，中小学教师编制管理中存在的有编不补，不增加额外编制，长期不调整编制，其核心原因在于县级政府控制用于基础教育的财政投入。

### 中小学教师编制制度的弹性空间降低了制度的刚性约束

中小学教师编制存在的问题也与中小学编制管理制度存在很大弹性有关。这表现在以下方面：其一、中小学教师编制管理规定的效力等级不高，国家与地方层面的都是规范性文件，强制效力不强。其二、中小学教师编制文件中多是鼓励性的规定。比如说1984年的中小学教师编制标准规定明确说明该编制标准"供各地研究制定编制标准时参考"。2001年编制管理文件规定"中小学校的管理工作尽可能由教师兼职，后勤服务工作应逐步实行社会化"，2014年的编制文件规定"鼓励有条件的地方，探索将一般性教学辅助和工勤岗位不再纳入编制管理范围"，"对适合社会力量提供的工勤和教学辅助等服务，鼓励探索采取政府购买服务方式"。其三、规定不够具体明确，地方政府有很大自由裁量空间。比如2001年的规定考虑寄宿、病产假等因素"按照从严从紧的原则适当增加编制"；2014年文件中提到工勤和教学辅助岗位"纳入当地政府购买服务指导目录，所需资金要通过合理渠道和方式妥善解决"；再比如说动态调整问题，无论国家的文件还是地方的文件仅是原则性的强调，并没有设计动态调整的条件和调整周期等内容，即使有相关规定，地方政府也很少调整。

## 中小学教师编制管理法制化的基本问题

### 中小学教师编制管理法制化的可行性

中小学教师编制问题不仅是根据多少学生确定多少教师的问题，也不仅是设定特定身份进而分配相关待遇资源的问题，更重要的是它涉及到不同层级政府之间在教育公共服务的保障责任分配问题，也涉及到不同层级政府之间和政府各部门之间的权力运行问题。一个合理有效的编制管理制度需要协调政府内部不同部门以及不同层级政府之间在编制管理的职责与权力的设定问题。编制法制化是实现这一目标的重要方式，即将编制管理相关主体之间的权力与职责以法律法规的形式确定下来。编制管理法制化同样是解决中小学教师编制结构性缺编、有编不补和在编不在岗等问题的重要选择。但因其涉及重大利益和重要主体的权力配置问题，编制法制化依然在推进之中，2018年《中共中央关于深化党和国家机构改革的决定》亦提出"推进机构编制法定化"。

本文无法探究整体上编制法制化的推进问题，但认为推进中小学教师编制管理法制化是推进我国事业编制管理法制化的一个可行的切口。首先，政府有义务保障基础教育发展，保障每一个公民受教育权的实现，这是基本共识，也是我国《宪法》《教育法》《义务教育法》所确定的政府的基本任务，国家最新的政策文件中也确定其是基本公共服务。不像其他一些事业单位，其是否应当由政府来举办，还存有争议。其二、随着中小学教师公开招聘制度的实施和完善，相关配套制度已经健全，教师招聘流程的公开公正有效制止了权力的滥用，加之中小学教师编制对地方政府是一种义务，权力滥用的可能性较小。其三、推行中小学编制管理法制化，还有一个操作上的优势，基础教育有特定的服务对象，有特定的工作内容，中小学教育教学所需的教师数量是可估量的，通过科学测量是可以设计出中小学教师的编制标准的。其四、中小学教师编制是地方政府事业编制的重要组成部分，推进中小学教师管理编制法制化的试点经验，有助于其他事业编制，甚至行政编制，推进法制化。事业编制法制化改革并不需要等各类事业单位编制改革的条件都具备才可以推行，可以选择特定领域的事业单位为突破点。比如说事业单位工作人员的绩效工资改革最初也是从义务教育阶段教师开始试行的。

### 中小学教师编制管理法制化的基本内容

编制管理是规划管理的重要方面，是具有区域性差异和动态变化特征的事项，编制数额与中小学校布局结构和学龄人口的变化息息相关，而法律作为一种稳定的制度规则，应当规定一些普遍性且稳定性的内容。因此，编制管理法制化的内容主要解决的问题不是具体确定编制多少的问题，而是不同主体在编制管理过程中的职责与权力配置问题。具体而言，中小学教师编制法制化应当解决以下几个问题：第一，谁来制定中小学教师编制标准和核定程序？第二，谁来核定中小学教师编制？第三，谁为中小学教师编制买单？第四，谁来监督中小学教师编制的实施？解决以上问题，会涉及到三对关系：不同层级政府之间的权力分配问题，政府内部各部门之间的权力分配问题，政府与民众之间的关系问题。回答以上问题要把握一些基本的价值准则，即保证政府提供基本均衡的基础教育公共服务，保证财政事权与支出责任的相匹配，保证支出责任和支出能力之间的匹配关系，还要把握让掌握信息的人进行决策，让做事的人有决策权。

## 中小学教师编制管理法制化的具体建议

### 中小学教师编制标准和程序制定权的分配

中小学教师编制标准及核定编制的规则应当由中央政府确定。因为基础教育属于中央政府和地方政府共同的财政事权，为了保障教育资源的公平享有，满足公民最基本的受教育权。且基础教育投入很强的外溢性和收益的滞后性，地方政府缺乏很强的内生投入动力。中央政府确定基本的编制标准并监督地方政府按标准核定编制是保障地方政府基础教育投入的重要手段。中央政府的中小学教师编制制度应当分布在两个层面，一个是法律层面，一个是行政法规或规章层面。法律层面，应当明确实施编制标准制度，规定编制标准的制定主体与程序。关于编制标准制定主体，现有中小学教师编制标准由编制部门、教育部门和财政部门共同制定，法律层面应当确定由教育行政部门主导，由编制部门审核。关于程序方面，应当确定定期调整制度，涉及编制调整启动条件和启动主体的设定问题，需要在法律层面赋予教育行政部门在法定条件下提出重新核定编制的权力，也需要明确在法定条件满足时，编制管理部门必须进行核编的义务。只有这样才能使得地方政府及时地根据教育事业发展的新情况，有计划调整编制配置工作。在行政法规层面，因中小学教师编制管理涉及教育、人事、财政和编制部门，制定行政法规才能更好统筹各部门之间的职责分配，另一方面，行政法规修订程序比法律更容易一些。在行政法规层面，需要明确中小学编制的标准和地方政府核定编制的程序，以及在何种条件下，由什么主体可提请重新修订编制标准。中小学教师编制标准，应当设定一定区间，省级政府可以根据本省实际进行调整。省级人民政府应当以地方性法规的形式制定实施中小学教师编制标准。市县政府也应当各自在中央与省级规定制定本市或本区县的中小编制标准的实施方案，并向社会公布。

### 授权县级人民政府核定中小学教师编制总量

中小学教师编制的核定权应当下放给中小学校的举办者，考虑到基础教育以县为主的管理体制，应当将中小学教师编制的核定权完全下放给县级人民政府。根据现行编制的分级管理原则，县域内中小学教师编制由县编制委员会核定，但因"总量控制"原则，该编制核定权并不具有真正意义上的核编权，而是在总量确定之后的分配权。为什么要把中小学教师队伍编制的核定权交由县政府？第一、县级政府作为基础教育的组织单位，对基础教育的人力资源需求最为了解；第二、基础教育实行以县为主的财政保障政策，中小学教师工资由县级财政保障，县级政府比较了解自身财力，可以量力而出；第三、现在把中小学编制总量的核定权放在省政府，主要是为了防止编制腐败，但基础教育领域盲目扩编的问题并不严重，加上中小学教师公开招聘制度的不断实施和完善，进人舞弊现象得到制止。 总量控制原则恰相反限制了部分财力充足，又愿意增加编制的县。第四、把核编权完全交给县级人民政府，不再适用总量控制原则，并不是说县级人民政府完全自由地核定中小学教师编制，县级人民政府是在中央、省级人民政府制定的编制标准和程序下，核定中小学教师编制，这样使得对编制管理的监督由事前监督转向事后与事中监督。

由县级人民政府核定中小学教师编制总量将有助于提高中小学教师编制核定的计划性。缺乏对未来教师需求结构的远景预测是中小学教师在学科、年龄、职称、性别等方面面临结构缺编的根本原因。因为中小学教师一旦入编，其职业具有较强的稳定性，这是教师职业成长的需要，也是教师职业吸引力的重要因素，在不改变教师职业稳定性的制度的情况下，要保障教师队伍结构的合理性，就必须提高政府对于未来教师需求结构的预测的准确性，因此，教育行政部门要对本区域未来5年学生人口变化情况、流动情况、学校的布局结构变化情况有所预测，以长远的目光核定当年的新教师编制数，为实现此项工作需要建立相应的数据支持系统。

### 改革中小学教师人事聘用关系的学校属性

改变中小学教师与学校签订聘用合同的规定，将聘用合同的签订主体由学校变更为教育行政部门，这样才能打破教师人事关系的学校属性，赋予县级教育行政部门可根据学校学生人数变化，统筹教师在学校之间的使用，另外要调整相应的学校绩效工资制度和职称制度，减少学校之间在绩效工资和职称指标分配上的差异，还需要赋予教育行政部门在教师人事调动方面更多职权，只有这样才能解决教育行政部门校际间分配教师资源的阻力和人事调动的成本，解决教师在校际间结构性缺编问题。为此，则需要对《教师法》的第十七条进行修订。

### 中小学教师编制单列管理

中小学教师编制管理应当单列管理，独立于其他事业单位。单列管理是指中小学教师编制标准、核准程序单独规定，且中小学教师编制数量总量单列，不与其它事业编制加总核定。为什么说中小学教师队伍的编制要单列？第一、能够使中小学教师队伍的编制管理制度根据教育事业改革发展的实际及时有效地调整，不被其他事业单位工作人员编制改革掣肘；第二、能够确定中小学教师的编制用在教育教学岗位上，防止其他事业位挪用中小学教师编制；第三、编制单列管理是上文提到编制标准制度与核定程序进行重新设定的前提，因为如果不是单列管理，上文建议的制度改革不可能在事业编制管理制度之下突破；第四、最为关键的是编制数量单列核定并公布时，民众才可以进行监督。

### 构建责任明晰中小学教师工资保障体系

建立健全中小学教师队伍工资保障体系是解决编制短缺的治本之策，编制问题本身是财政问题，很多县域中小学教师编制问题是由于县级财政经费紧缺，必须建立保障有力的中小学教师队伍工资体系。县级政府不缺经费时才有能力扩充编制。现行的特岗教师改革则说明了这一点，因为特岗教师前三年的工资待遇的大部分由中央财政专项拨付，所以地方政府有很强招聘特岗教师的动力。现行中小学教师工资主要由县级财政承担，但中央政府或者省级政府对财力薄弱的县有一般性转移支付，县级政府在一般性转移支付的使用上有很大的自主权，无法知晓其是否以及多少将一般性转移支付用于教师工资，增加教师编制。为了促进县级政府增加编制，可以将中央政府的一般性转移支付的一部分设定为教师工资专项补助，与教师数量挂钩，中央政府承担地方政府新增中小学教师工资的一部分，根据地方财力确定中央政府承担的比例。中小学教师工资保障机制的建立涉及不同层级政府之间的财政与税收权力配置问题和地方财力的测算问题，远不是本文所能完全阐释。但本文强调的是解决中小学教师工资保障机制问题对解决中小学教师编制缺编具有至关重要的意义，需要得到研究者和政策制定者的重视。

### 建立有效的中小学教师编制管理监督体系

编制管理的监督体系不健全是现行中小学教师的编制管理存在问题的原因之一。对于"有编不补"的问题，其违规主体是县级政府，按照核定的编制配置教师是县级人民政府的责任。不根据情况重新核定区县中小学教师编制总量，责任在于上级政府。关于"在编不在岗"的情况，一是行政部门的违规使用，借调在编教师承担教育行政管理工作，更有甚者借调教师到县组织、宣传、扶贫等相关部门工作，此时的违规主体是县教育局或者其它行政部门；"在编不在岗"也存在于学校层面，学校违规"默许"教师在编不在岗，或者由他人顶替岗位的情况。针对学校存在的违反编制管理规定的行为，可由教育行政部门和编制管理部门进行检查监督。但教育行政部门或者其它行政部门存在的违反编制管理规定的行为，甚至县政府本身存在的有编不补的问题或者上级政府不随情况变化重新核定编制的行为，因为各级编委的高规格组成，对各级人民政府不作为的同级内部监督是没有意义的，需要建立另外的监督机制。

中小学教师编制管理应当建立以下监督制度。第一，建立编制信息公开制度，加强公众监督。为了使公众能够监督，应当建立编制管理规则和核定结果的公示公开制度，这一制度需要在法律层面明确，只有这样才能形成有效的公众监督。而现在中小学编制核定的规则、程序与结果都是不公开的，再加上中小学教师编制管理很大程度上是在行政系统内部进行的，不涉及具体的行政相对人，不利于公众进行监督。中小学教师编制管理的核心目标是保障公民受教育权的实现。因此，编制管理流程应当公开，接受公众的监督。除了民众监督以外，还应当加强人大的监督。法律规定各级政府预算要经过人大审议通过，因为编制意味着政府的财政拨款，由人大对编制管理进行监督是落实预算制度的本质要求。地方政府向人大提交的预算报告中要明确说明每年由财政支付工资的编制人数，其中包括中小学教师，由人大督促地方政府按照法定标准和程序确定地方中小学教师编制。第三，现行中小学教师编制管理的监督主要是以总量控制的上级政府监督模式，这种模式存在的问题上文已做论述，但这并不意味着摒弃上级政府的监督，可实行其它形式的上级政府监督，比如授权上级教育行政部门和编制行政部门对下级教育行政部门和编制管理部门执行编制标准及相关规定的情况进行检查和监督。第四，要明确有编不补，不及时核编，挪用编制等违规行为的法律责任。没有法律后果的禁止性规定效力不大，虽然国家对挪用编制三令五申的禁止，却始终没有解决编制挪用问题，重要的原因在于违反规定并不承担责任。因此，必须通过法律的形式来明确违反编制管理要求所应承担的法律责任，提高禁止性规定的强制性效力。

## 参考文献

周兆海,邬志辉.工作量视角下义务教育教师编制标准研究------以农村小规模学校为例[J].中国教育学刊,2014,(09):1-6.

柳丽娜,朱家存.中小学教师编制城乡统筹研究[J].教育与经济,2009,(04):39-42.

李宜江.农村教师编制动态管理有效路径探析[J].中国教育学刊,2013,(06):32-35.

邬志辉,陈昌盛.我国义务教育阶段教师编制供求矛盾及改革思路[J].教育研究,2018,39(08):88-100.

杨卫安,袁媛.义务教育教师编制"市域调剂"的障碍与改革思路[J].中国教育学刊,2019,(08):35-38.

张宗倩,秦玉友.供需增量:县域教师编制的现实挑战与政策议题[J].中国教育学刊,2020,(08):71-76.

刘善槐,朱秀红,李畇赟.农村教师编制制度改革研究[J].中国教育学刊,2019,(01):7-12.
