---
title: "Untitled"
author: "yy"
date: '2022-03-14'
output: html_document
---

因为职称的是个体的能力的标识，不是一种岗位，因为对于教师而言，其具有了流动性，即职称不仅在一个学校有效力，职称应当在一定范围内有效力，即职称评审结果在哪些空间范围有效的问题。确定合理的范围应当保证职称的认定在该范围内是基于同一标准，具有可比性。1991年人事部关于《<企事业单位评聘专业技术职务若干问题暂行规定>有关具体问题的说明》中提到"哪里评哪里有效"的原则。这一基本原则是合理。虽然中小学教师职称有国家层面的规定，但是各省有更细化且不同的标准，且评审工作是在省级统筹的基础上进行的。而且中小学教师职称评审分级评审的问题。比如二三级职称是区县评审，那么是否本区县有效，高级职称在市域有效，正高级职称在全省有效。考虑到中小学职称评审在全省有着统一的标准，中小学职称评审应当坚持在职称评审所在省全省的效力。

专业技术职务是工作岗位，"聘任"或者"任命"是指将专业技术人员安排到相应专业技术职务相对应岗位的过程。专业技术人员在被聘任或者任命之前，需要经过一个评定的过程。赋予职称的岗位属性之后，在操作和逻辑上创造了两个不同的步骤：一是评审，一是聘任。这也是后来实行"评聘分离"的基础，即职称可先评定，没有岗位时不聘任，有岗才聘任。

教师评价的一部分，但并不是全部，，是工资制度的前提。因此，职称制度存在的问题，并不仅仅是职称制度的问题，而是教师评价制度的问题，和工资制度问题。关于教师评价的问题，比如，教师的师德、能力和业绩如何评价，是否可以评价，各占多少分？教师之间的能力差距有多大？业绩差距有多大？如何评价教师的业务能力？这些问题是教师评价的问题？但是职称作为教师评价的重要聚合点，所以就变得问题比较多？

因此需要建构符合中国国情的理论框架。 如果在尊重劳动力市场规律情况下，重塑教师这个职业，合理设定其工资水平、工作职责（合法确定其职责的边界）、职业权利（合法的权益保障）、职业发展，职业阶梯。 则是我们进行教师队伍建议应当遵循的步骤。毕竟在一个开放的职业市场里，选择教师这个职业、和离开这个职业已经成为个体的一种选择。个体对于这个职业的反馈与定位最终会决定这个职业最终从业者的质量。

## 聘用的约定事项

现实当中一般情况下，中小学教师很少用到《聘用合同》，很多教师甚至不知道自己有合同，即使有的，也觉得没有多少用处。真正使用聘用的时候，主要是聘用合同履行出问题的时候。问题的核心在于聘用合同哪些内容是合同的部分，即合同的双方可以协商与变更的部分。如果合同的内容完全由一方事先决定，且一定行政区域内、甚至全国教师执行同样的约定，签订的合同意义何在，直接制度国家层面或者区域层面的规定就可以了。因此，必须基于已有的实践来分析，聘用合同可约定的事项有哪些？

岗位约定的问题。岗位职责对于中小学教师而言，将涉及教师任教学科、班主任、和学校行政任务的安排问题。在中小学老师

## 聘用合同纠纷的救济与法律适用

何谓"履行聘用合同纠纷"，纠纷合同解除纠纷的处理。

是走行政诉讼，还是人事争议仲裁程序的问题，人事法律、和劳动法的混合适用的问题。完善事业单位人事管理的基本法，和特殊事业单位工作人员的专门法。以适用事业单位工作人员的基本法和专门法为主。
