---
title: "弥合校企信息鸿沟　促进职业教育发展"
author: "yy"
date: "1/7/2022"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

# 引言

职业教育是我国人力资源开发的重要组成部分，肩负着培养技能人才、促进就业创业、推动经济转型升级的重要职责。为推动职业教育发展，《中共中央办公厅、国务院办公厅关于推动现代职业教育高质量发展的意见》提出要"坚持产教融合、校企合作，推动形成产教良性互动、校企优势互补的发展格局；坚持面向市场、促进就业，推动学校布局、专业设置、人才培养与市场需求相对接"
。但职教发展一直存在产教融合不畅、校企合作不强的问题，导致"人才培养供给侧和产业需求侧在结构、质量、水平上还不能完全适应"。产教融合不畅的原因之一在于校企技能人才供需存在信息鸿沟。市场经济改革之初，培养人和使用人由政府规划，政府同时管理企业与学校，既了解企业用人需求，也能决定职业教育的规模和结构，比如，九十年代中期之前的技工学校在产教融合、校企合作方面是非常有效的。但随着市场经济发展，职业教育毕业生更多进入民营企业，劳动力市场对技能人才的需求信息无法有效地传递给学校，学校供给的技能人才也开始无法满足劳动力市场的需求。近年些来，职业教育改革方向是向职业学校放权，由学校自主设置专业、课程和人才培养方案，以提高其主动适应劳动力市场人才需求的能力。但劳动力市场对技能人才的需求规模与结构涉及区域性与全国性的信息整合，且随着技术革新和产业布局与结构调整而不断变化，作为独立个体的学校无法准确把握劳动力市场的技能人才需求信息。同时，企业在选址或业务调整时也无法全面知晓技能人才供给信息。总之，校企在技能人才供需上存在信息鸿沟。构建校企信息沟通的有效表征指标，建立技能供求信息的收集、共享机制，弥合校企信息鸿沟是促进产教整合、校企合作的奠基性工作，对促进职业教育发展具有重要意义。

# 弥合校企信息鸿沟是实现产教融合的重要基础

产教融合、校企合作的实现需要各个学校与企业的科学自主决策。决策的基础是信息，信息充分才能保证决策的科学性和准确性。学校的专业设置、课程开发、教学设计等决策需要了解区域性甚至全国性技能人才需求的规模与结构等信息。企业的布局、技术更新和产能调整等决策同样需要把握可供给的技能人才的水平、规模与类型等信息。如果学校与企业不能获得有效的信息，供需错配会造成很大损失，比如，学校在没有充分信息的情况下，盲目新增热门专业，培养的人才不符合劳动力市场的需求，既导致教育资源的浪费，也影响毕业生就业及就业质量。

弥合校企信息鸿沟迫切需要政府出场，承担技能人才供需信息的收集、分析与共享的职责。首先，只有政府才有资源和条件获得区域内甚至全国范围内的技能人才的供需信息。其次，技能人才供需信息的共享有利于促进就业和社会经济发展，就服务公共利益而言，也应当由政府承担这份职责。再者，由政府承担信息收集责任的另外一个原因是，基于自身利益最大化，学校和企业在合作中都会隐藏对自己不利的信息，比如学校可能虚报毕业生质量的数据，政府能以更中立的立场收集校企双方的信息。最后，提供公共数据既是建立服务型政府的重要举措，也是提高政府治理能力和决策科学化的重要基础，国务院办公厅印发的《要素市场化配置综合改革试点总体方案》也提到："建立健全高效的公共数据共享协调机制，支持打造公共数据基础支撑平台，推进公共数据归集整合、有序流通和共享。"

# 构建准确的数据指标是校企信息互通的技术保障

实现校企技能人才供需信息全面、有效与精准互通需要设计有效的信息表征指标。在技能人才需求侧，我国和世界上其它国家常常以从业人口的行业结构和职业结构来度量，根据《国民经济行业分类》（2019年修改版），行业被分为20个门类、97个大类、473个中类、1382个小类，根据《国家职业分类大典》（2015年），职业被分为8个大类、75个中类、434个小类、1481个职业。为掌握劳动力需求状况，国家也实施了《全国月度劳动力调查》，但《中国人口和就业统计年鉴》共享的全国劳动力需求信息仅包括20个行业门类和8个职业大类，该数据无法精细地反映劳动力市场对技能人才的需求结构，对职业院校专业设置、课程设计等指导意义不大。地方性的数据还比较缺乏，且公开数据的可读性与可及性也较差。除以行业与职业维度度量劳动力市场技能人才需求结构之外，世界上主要国家都开始关注劳动力技能需求结构的测量工作，比如经合组织（OECD)2011年已经开始实施的成人职业技能调查项目（PIAAC），对劳动力市场的技能需求情况进行评估，美国职业信息网络项目（O\*NET)离析了各职业中的161项技能类型，并分析其在各职业中重要性占比。以技能表征劳动力市场的需求结构，可以更精细、准确地描述劳动力市场对技能人才需求的数量与结构，有利于职业学校确定招生规模、专业设置、课程设计、师资配置等工作。技能人才需求侧的信息还包括职业教育毕业生就业质量信息，涉及工资待遇、技能匹配度、职业满意度等，这些信息也可以有助于学生选择接受职业教育的学校、区域、专业等。以上关于劳动力市场需求结构的数据都同时涉及需求的空间分布和变化趋势的统计与预测问题。

在技能人才供给侧，职业教育的招生、在校生、毕业生的数量以及专业分布可以用来表征技能人才的现实或潜在的供给信息。专业是描述职业教育毕业生知识水平和技能类型的重要指标，也是"职业教育支撑服务经济社会发展的重要观测点"，最新版《职业教育专业目录（2021年）》统一采用专业大类、专业类、专业三级分类，共设置19个专业大类、97个专业类、1349个专业，其中，中职专业358个、高职专科专业744个、高职本科专业247个。可惜的是《中国教育统计年鉴》公布的只有全国的专业大类的职教毕业生数据，该数据对学校设置专业、企业评估技能人才供给等功能有限，比如装备制造大类下面有机械设计制造、机电设备、自动化、汽车制造和航空装备等7个专业类，专业类下还包括68个专业，这些专业细类中毕业生的分布情况信息尚末公布，获取地方性的毕业生分布的信息也比较困难，不利于职业学校根据技能人才需求服务于地方经济发展。

# 全流程施策构建校企信息互通共享机制

为做好技能人才供求信息的收集、分析与共享工作，政府可以从以下方面着力：其一，指定政府专门部门具体承担该项职责，并拨付专项财政经费。项目实施过程中需要多部门协作，因为相关工作会涉及教育行政部门、人力资源综合管理部门和统计部门的业务领域和职权范围。这项工作也是这些部门各自履行促进职业教育发展、促进就业创业和为社会经济发展提供数据支撑的职能需要，各部门利用各自优势、高效协作，才能实现优势互补。《要素市场化配置综合改革试点总体方案》提出"探索完善公共数据共享、开放、运营服务、安全保障的管理体制"，可以此为契机建立技能人才供需信息的生成与共享的管理体制。其二，在数据收集方面，既要做好行政管理过程中行政管理数据的收集、统计工作，也要做好专项微观抽样调查工作，比如，职业教育毕业生的数量、层次和专业类别等信息属于行政管理数据，而毕业生就业质量、劳动力市场岗位技能需求的数据则需要通过科学设计的抽样调查来获取；既要做好地方性的劳动力市场技能人才供需信息的收集，也要做好全国性数据的收集；在数据收集过程中，要发挥行业组织的作用。其三，在数据分析、共享方面，要提高信息的可读性与可及性。政府部门需要对数据进行分析、形成报告。建立一站式的数据共享和报告发布平台，统一信息发布。针对普通民众，可以采取月度、季度或者年度报告的形式呈现，以简洁的表格，同时充分利用数据可视化和网络技术，对数据进行可视化、交互式地呈现，以提高数据的可读性与可及性。针对具有数据分析能力的受众，比如科研人员，提供完整、格式友好的原始数据。信息共享不仅要做好对当下劳动力市场中技能人才需求现状信息的共享，同时需要运用经济理论和统计方法对未来技能人才需求进行预测，发布预测报告。完善信息表征指标体系，建立技能信息和职业信息的动态更新机制。其四，进一步加强技能人才供给与需求信息的表征指标的研究，提高信息的精细度、精准度，比如，如何对技能定义、分类、测量需要系统的理论建构；理论上厘清专业与职业之间的联结关系，设计合理的匹配方式；加强对劳动力市场未来需要的预测模型研究，如人工智能技术对劳动力技能需求结构的影响迫切需要实证数据预测与论证。

（作者：叶阳永，系中国人民大学教育学院讲师，本文系北京市社会科学基金项目青年项目（17JYC027）研究成果。）
